- client/js/widgets/label.js
https://github.com/ArnoldSmith86/virtualtabletop/issues/3#issue-774905053
Parse the text field, assume 0 if unparsable (e.g. text)
> Fix inc/dec when counter

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- README.md
- SECURITY.md
- client/js/widgets/button.js
- package.json
Enable COUNT to be used to do some math
Includes files to enable security analysis and dependa-bot
Corresponding Tutorial:
* [Buttons-count.vtt](https://github.com/ArnoldSmith86/virtualtabletop/files/5754481/Buttons-count.zip)
Tasks:
> Add sum property to COUNT

- client/room.html
Yeah!! That's actually not that hard..
> Added discord link to "About" overlay

- client/js/widgets/button.js
Does this improve the result of SORT?
> reversed the order before SORT

- README.md
- jest.config.mjs
- tests/client/button-click.test.js
- tests/client/button-count.test.js
- tests/client/client-util.js
- tests/client/setup.js
Includes refactor of common code
> Add unit test for button CLICK

- README.md
Do those Windows steps work? I have no machine where I could test them.
> added license details and Windows installation steps to README.md

- client/js/widgets/button.js
If you use buttons as functions, you can use this parameter to click them multiple times. This makes it possible to read the count of clicks from a variable.
> added parameter count to CLICK

- client/js/widgets/button.js
I think it's reasonable to assume that anyone would expect the sum of a property of an empty collection to be 0.
> GET with sum returns 0 for an empty collection (fixes #112)

- client/js/widgets/button.js
> fixed that CLICK doesn't check if the widget has a click function (fixes #142)

- server.mjs
- server/fileloader.mjs
- server/pcioimport.mjs
- server/room.mjs
This should make sure that users can't access files on the server they shouldn't. Please test all download and upload buttons you can find. :D
> sanitize room, state and variant IDs to prevent file system breaches

- server/room.mjs
> fixed state download (fixes #186)

- client/js/widgets/button.js
Added a thisID variable to default Variable object.
Added thisButton to default collections object.
> Enhancement #146 add a thisID and thisButton

- .gitpod.yml
- .theia/launch.json
- .theia/settings.json
- README.md
- package.json
I want to be able to develop on my Android tablet and a web IDE seems like a good way to do that.
[Gitpod.io](https://gitpod.io) looks like it works just fine and this PR adds a few config files for it so that pretty much everything should just work.
An interesting feature is live collaborative coding. I'm looking forward to testing that with someone.
> presets for online IDE Gitpod

- client/js/widgets/button.js
Eliminate duplicate applyVariables code in #214 and fix the problem of `problems` not being passed into `showInputOverlay()`
> Eliminate duplicate applyVariables code in #214

- client/css/widgets/card.css
> don't hide card child widgets

- client/js/mousehandling.js
> Fixes click off bug

- client/css/widgets/spinner.css
Don't know why this toook me so long to do
> Change spinners value disc size to better fit the arrow svg

- client/js/widgets/button.js
This PR adds applyVariables to any fields used in the INPUT operation.
> added applyVariables to Input fields

- client/css/jsonedit.css
- client/js/jsonedit.js
This PR introduces buttons for all commands in the right panel of the json editor.
> buttons for json editor

- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
Allows FLIP operation to override the faceCycle property of the items in the holder.
Introduces new faceCycle option `backward` (reverse direction).
Introduces collection parameter to FLIP operation.
Closes #62
> Improvements to FLIP

- client/css/widgets/button.css
- client/js/widgets/button.js
Again I'm moving the PR to the original repo as I can't make changes from mine. I'll be closing the last PR #261
> Extend image and svg replace to buttons

- tests/client/client-util.js
- tests/client/widget-click.test.js
- tests/client/widget-count.test.js
Fixes automated tests for #197
> Update tests for button.click -> widget.click non-async

- client/js/jsonedit.js
- client/js/widgets/button.js
- client/js/widgets/widget.js
I needed a simple way to append text to a label rather than to replace it, so I added another mode.
> add append mode to LABEL

- client/js/main.js
- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
This fixes that a lot of properties would not trigger DOM updates when they are used as dynamic card face properties or as `svgReplaces` properties.
> card property changes get applied to dynamic face objects now

- client/js/widgets/button.js
> fix validID problem in applyVariables

- client/js/widgets/widget.js
Last minute changes _always_ screw everything up. :(
> fixed undefined collection after CALL and thisID+thisButton now point to the callee

- client/js/widgets/widget.js
Previously only the first found deck would be recalled.
> RECALL now works with multiple decks in a holder

- client/css/widgets/classes.css
- client/js/widgets/spinner.js
The game pieces don't need an extra border.
Spinners applied the font size in the wrong function.
> fixed edit mode display of checkers and pin pieces and font size of spinners

- client/js/widgets/deck.js
> changes to cardDefaults, cardTypes and faceTemplates now take effect immediately

- client/css/widgets/button.css
Removed font-weight: bold from button.css, as it changed the size of every button label. Fixes #384.
> Remove font-weight change from #265

- assets/icons-white/hide side bar.svg
- client/css/layout.css
- client/js/main.js
- client/room.html
I was initially too lazy to implement the special case where the room cannot fill the whole width or height.
Now it should work as expected.
> fixed site layout when aspect ratio is close to 16:10

- client/js/overlays/states.js
- client/room.html
This should help a lot of new users and also direct them into using "save room state" later,
Pretty sure this will help every one in general
For testing you need to have an empty room
> Adds save room state button to empty room overlay

- client/css/layout.css
only the blue buttons are affected.
example:
> changes color of UI's blue buttons on hover

- client/css/layout.css
- client/room.html
Co-Authored-By: 96LawDawg <76912527+96LawDawg@users.noreply.github.com>
I just putting what @96LawDawg did into a PR.
It adds more information about copyright attributions and some information about online gaming, safety, and privacy policy.
> Update About overlay

- client/components/deckEditor.js
Two function calls of `p` slipped through.
> fixed deck editor after changeRoutine PR

- client/js/widgets/widget.js
Code refactoring for changeRoutine broke the code path where two piles are merged.
> fixed dropping a pile onto another pile

- client/js/jsonedit.js
> Fix typo, getUniqueWidgetID -> generateUniqueWidgetID

- client/js/jsonedit.js
- client/js/widgets/basicwidget.js
- client/js/widgets/card.js
- client/js/widgets/pile.js
- client/js/widgets/spinner.js
- client/js/widgets/widget.js
modes are:
- 'respect' (default) : respects clickable false and executes ClickRoutine if available when clickable is true
- 'ignoreClickable' : ignores clickable false and executes ClickRoutine if available
- 'ignoreClickRoutine' : respects clickable false and ignores ClickRoutine and executes original click function
- 'ignoreAll' : ignores clickable false and ignores ClickRoutine and executes original click function
note that ignoreClickRoutine and ignoreAll make CLICKing a button pointless
> adds mode to CLICK

- client/js/jsonedit.js
I also didn't know how to make the last item as it would require a new function
Please check line 477. It is functional but maybe I did it too ugly, I can't use [A-Z]+ because not all functions should be included
> Update JSON editor

- tests/testcafe/tests.js
- Fireworks: Add new game, similar to Hanabi, by ArnoldSmith86
- Magician: Add new game, similar to Wizard, by ArnoldSmith86 and Ingegneus
- Pairs: Add new game, similar to Memory, by Ingegneus
- Functions – CALL: updated one of the comments in the “Rotate Widgets” button to correctly reflect how random works
- JSON User Guide: Add new tutorial to explain JSON Editor
Public Assets:
- Add new variant to Other Widgets. Adds Coordinate Helper, by Interitus
> Add Fireworks, Magician, Pairs

- client/js/editmode.js
I was passing by it in the code and decided to propose the change
- This PR:
- Before:
> gamepiece are in hue order

- client/js/jsonedit.js
Sooner or later I will expand this but for now it just adds two simple buttons: one adds `"var increment = ${variableName} + 1"` and one adds `"var random = randInt 1 10"`.
I also removed `RANDOM` from the JSON editor commands.
> added simple JSON editor command to add a dynamic expression

- tests/testcafe/tests.js
- Tic-Tac-Toe-Tye. New game by LawDawg.  Similar to Otrio
- Alleys. Updated with css rotation animation for game pieces.
- Stratagem. Updated with css rotation animation for game pieces (and improved again after Dev Game Night).
- Backgammon. Improved the doubling die and score keeping and tweaked the offsets in the holders on the right (after Dev Game Night).
- Array.  Modified library image and name.  This is no longer a function under COMPUTE, but a separate explanation of how arrays work.  Also, when switching to dynamic expressions, some of the code on all 3 variants was not optimized.  Fixed all of that. Created new variants consistent with the Strings tutorial.
- Strings. Added new tutorial based on dynamic expressions.
- Comparisons. Added new …
> Add Tic-Tac-Toe-Tye, many tutorials

- client/js/jsonedit.js
See #534. The minifier does not like "$" in certain places. I have no idea why.
> fixed server crash after PR #530

- client/js/editmode.js
The "grey" preset wasn't working because we were looping through 5 indexes but their were 6 items to check.
> fix canvas presets

- client/js/editmode.js
- client/js/jsonedit.js
- client/js/widgets/widget.js
There are multiple situations where widgets were not completely removed when they should have been. This PR aims to fix those instances.
> fixed phantom widgets after removal

- client/js/widgets/widget.js
- server/room.mjs
We discussed this in a meeting long, long ago.
Please note that this can only set the name and color of the player triggering the routine.
> variables playerName and playerColor are now writable

- client/js/widgets/timer.js
- server/room.mjs
Timers react a lot better to changes done by other players or through the JSON editor.
I also added that the first player to enter a room automatically starts all the timers that are not paused.
> improved timer behavior

- client/css/editmode.css
- client/css/widgets/canvas.css
- client/css/widgets/label.css
- client/js/domhelpers.js
- client/js/editmode.js
- client/js/jsonedit.js
- client/js/mousehandling.js
- client/js/serverstate.js
- client/js/widgets/canvas.js
- client/js/widgets/pile.js
- client/js/widgets/timer.js
- client/js/widgets/widget.js
- client/room.html
- package-lock.json
- package.json
- server/minify.mjs
- server/room.mjs
- tests/testcafe/tests.js
- Chinese Checkers. Fixed one holder and added clickable turn indicator following dev game night comments.
- Medieval VNO. Swapped the default rotation for Next button (in Automation variant) to clockwise.
- Reward. Removed about 1,000 cards (game tokens) and replaced with clones.
- Arrays (Creating). Changed text of button from GET to example dynamic expression (not caught earlier when JSON was updated to move away from GET, SELECT to var x …
- Button Appearance (Introduction).  Fixed typo switching left and right.
- faceTemplates. New tutorial by Interitus that shows how to use dynamic expressions to modify faceTemplates.
- Functions - FOREACH. New tutorial by Interitus showing how to use the FOREACH function and loopRoutines.
- Slightly modified …
> Add Tutorials (faceTemplates, FOREACH)

- client/js/widgets/label.js
fixes #589 
Also changes twoRowBottomAlign so that it is not dependent on label height - should bottom align any size label.
> Fix `twoRowBottomAlign`

- client/js/jsonedit.js
The minifier strikes again. We really need an automated test with production settings.
> fixed server crash after #552

- client/js/jsonedit.js
Adding '${}' in places in the JSON editor where variables are frequently used.
> Adding  '${}' in JSON editor

- client/js/widgets/widget.js
Protect all writes to debug log with 'if debug set' to avoid spurious writes to debug buffer. Fixes #649.
> Prevented spurious writes to debug buffer

- client/js/widgets/holder.js
- tests/testcafe/tests.js
The code is really not pretty but it seems to fix the issue for me. I really hope one day somebody comes along with a perfect solution for all that pile+holder mess.
> fixed card order when dropping a pile into a hand

- client/js/jsonedit.js
moves fixedParent under parent in the JSON editor.
> fixedParent under parent

- client/js/editmode.js
This should do the exact same thing as PR #709, however, I realized this would be a more concise way of doing the same thing since it was repetitive before.
If this method is preferred, then I can merge this PR into that one.  Otherwise I can just close this one.
> More concise Edit Mode Adjustment

- client/css/widgets/canvas.css
This is to address issue #725.
> Moving border from canvas to canvas widget

- package-lock.json
- package.json
- server/websocket.mjs
Supercedes #732. It needed minor code changes to make the update work.
> updated ws to 8.2.0

- client/css/overlays/states.css
- client/js/overlays/states.js
- client/room.html
small improvement for now. as discussed in Discord
> style section titles in library list so they stand out

- client/css/layout.css
- client/css/overlays/players.css
- client/js/overlays/players.js
- client/room.html
Added  instructions and inactive player separator to room.
Added CSS to make layout more useful and place your name at the top and active players above inactive players.
> Re-layout of Players Overlay

- client/js/widgets/widget.js
> Select max widgets *after* pile resolution, not before.

- client/js/widgets/widget.js
What it says...
If approved, I'll update the Wiki as well.
> Change names of `absolutex` and `absolutey` to `absoluteX` and `absoluteY`

- client/js/widgets/seat.js
Applies colorEmpty to color when player leaves seat
> fixes colorEmpty

- client/js/jsonedit.js
Pretty basic stuff. This also prevents an error when `# Copies X` _and_ `# Copies Y` are set to `0`.
> changed minimum of duplication option `# Copies X` to 0

- server/fileloader.mjs
I am not sure how this happened but it was pretty obviously broken.
> fixed loading vttc files

- client/js/main.js
- client/js/mousehandling.js
- client/js/overlays/players.js
Closes #855 
This now broadcasts a message to mark the cursor inactive when an overlay is opened. Also changes the method for determining if the main mouse button is pressed when sending update (previously an overlay dismissed with a keystroke could cause the button to appear pressed even if it was not).
> Mark cursor inactive when in overlay

- client/js/widgets/widget.js
Modify the debug output for INPUT functions to actually display the names of the variables modified, and their new values. Fixes #885 .
> Fix debug information for INPUT

- client/js/widgets/widget.js
I think this fixes #872, but this needs code review from @ArnoldSmith86 .
> Protect set(parent,null) in MOVEXY by disablePileUpdateAfterParentChange

- client/css/layout.css
> Full screen API requires webkit-specific prefixes.

- client/js/widgets/widget.js
Adds clickSound
@bjalder26  please check if you want to improve the code or if you want this at all
> Adds clickSound

- client/css/editmode.css
> Fix height of editmode JSON edit window

- client/css/layout.css
- client/js/editmode.js
- client/js/widgets/widget.js
- client/room.html
adresses #854
Not much about it. Just removed the checkbox in the HTML and the corresponding JS in editmode.js
> removes the debug check box in button edit overlay

- client/css/editmode.css
- client/room.html
Just improved the layout a bit. Feedback is welcome.
> more usable space for the classic JSON edit overlay

- client/js/widgets/widget.js
> `CANVAS` mode `setPixel` coordinate validation

- client/css/layout.css
> Fixed extra edit appearing.

- client/css/jsonedit.css
- client/js/jsonedit.js
A change to the markup caused `.jeTopButton:last-of-type` not to work anymore so adding the command options failed. I actually took the chance to finally improve the markup of the toolbar which also led to some CSS changes.
> fix JSON editor commands with options

- client/js/editmode.js
Missed at least one `await` in #917.
> fix adding composite widgets

- client/js/jsonedit.js
- client/js/widgets/timer.js
- client/js/widgets/widget.js
Adds mode to timer's click() in timer.js
Adds TIMER to the list of functions that accept "collection" in jsonedit.js
~Removes cold form old debug still remaining in TIMER~ fixed in #1000 
~there is still issue #998~
> Fix some timer problems

- tests/testcafe/tests.js
- Canvas. New tutorial explaining the CANVAS function and composed widget. 1 Variant
- Routines. Substantially revised the changeRoutines tutorial.  Now 4 variants covering all aspects of routines.
- Functions – AUDIO. New tutorial. 1 variant for AUDIO and clickSound
- Functions - CLONE and DELETE. New tutorial. 1 variant
- Functions – COUNT. New tutorial. 1 variant
- Functions – FLIP. New tutorial. 1 variant
- Functions – LABEL. New tutorial. 1 variant
- Functions – MOVE. New tutorial. 1 variant
- Functions - RECALL and SHUFFLE. New tutorial. 1 variant
- Dice. Added ArnoldSmith86’s version of the dice
Changed library image using new VTT icons for the following tutorials:
- faceTemplates, Grid, Hands, Holders, inheritFrom, JSON Editor User Guide (just adjusted text …
> Many new tutorials plus library image updates

- client/css/layout.css
- client/js/domhelpers.js
- client/js/widgets/widget.js
- client/room.html
- server/pcioimport.mjs
- tests/testcafe/tests.js
All the inputs you used to have and a few more. 
- `switch` works just like `checkbox`, but provides a different context.
- If no icon or text is provided for either the confirm or cancel buttons, the old defaults of "Go" and "Cancel" are used.
- The icons use the VTT-Icons class so only those icons are available for now.
- `subtitle`s are available to split things up if needed.
- `title`, `subtitle`, and `text` can be styled with `css`. The default styling is show above.
Input overlay items:
```
{
"func": "INPUT",
"fields": [
{
"type": "title",
"text": "Title"
},
{
"type": "text",
"text": "A simple text block."
},
{
"type": "checkbox",
"label": "Checkbox",
"variable": "checkboxInput",
"value": true
},
{
"type": "color",
"label": "Color picker",
"variable": "colorPicker",
"value": …
```
> New input overlays

- client/js/widgets/widget.js
Reverts changes to selection among multiple valid target holders introduced in #903.
> Select closest valid dropTarget

- client/js/jsonedit.js
The hotkeys were disabled anyway for now.
> removed highlighting of the hotkey from JSON editor

- client/js/statemanaged.js
Addresses issue https://github.com/ArnoldSmith86/virtualtabletop/issues/1026 . I do not think there is ever an appropriate time for the audio property to be inherited.
> Exclude audio property from inheritFrom

- tests/testcafe/tests.js
- Capture the Flag. New game by LawDawg. Similar to Stratego
- Interrogation. New game by Ingegneus. Similar to Guess Who?
- Bulls. Fixed movable “Get” buttons
- Functions – INPUT: New tutorial with 1 variant.
- Functions – MOVEXY: New tutorial with 1 variant.
- Functions – SELECT: Substantially revised. Now has 3 variants: basic, relation, and mode and rank.
- Routines. Fixed a couple of typos.
- Piles. Added comment about z-index:-1 in first variant. Addd mousewax cube example in last variant.
Public Assets:
- Symbols: New asset with 2 variants.
- Universal Game Symbols. Asset removed.
> Add Capture the Flag, Interrogation; other updates

- client/js/widgets/widget.js
> remove widget stylesheet when removing widget

- client/js/editmode.js
- client/js/jsonedit.js
- client/js/statemanaged.js
- client/js/widgets/card.js
See #1092.
This changes stuff pretty deep down. I'm pretty sure that this shouldn't change game behavior but this probably should receive more testing than "inheritFrom seems to work better now".
> fixed `inheritFrom` with default values

- client/js/editmode.js
- client/js/jsonedit.js
It saved me a lot of time when building `Crossed` so I thought it might be a good idea to include the macros I used as examples.
> add a few examples to the JSON editor macro feature

- client/css/fonts.css
- client/css/layout.css
- client/css/overlays/players.css
- client/js/connection.js
- client/js/domhelpers.js
- client/js/main.js
- client/js/overlays/states.js
- client/js/serverstate.js
- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
- client/js/widgets/pile.js
- client/js/widgets/spinner.js
- client/js/widgets/widget.js
- client/room.html
- config.template.json
- server.mjs
This supersedes #731. It uses code by @tsankuanglee. The PR base was pretty outdated by now and I wanted a different solution for asset URLs in hopes of reducing breakages in the future.
This basically adds the feature to put something between the domain and the room name in the URL by using `urlPrefix` in `config.json` (so for example `https://virtualtabletop.io/customPrefix/myRoom`.
This is useful if you want to host a VTT instance alongside other content. I want to use it for test servers so I do not have to create a new subdomain certificate for every new test server. When this gets merged I can change the PR test servers to be `https://beta.virtualtabletop.io/PR-1087/` and add test servers like `https://beta.virtualtabletop.io/unstable/` etc.
The main things that need to be tested …
> added urlPrefix config parameter

- server/minify.mjs
> load fonts.css after widget css

- client/js/widgets/spinner.js
> fix spinner bugs

- client/js/serverstate.js
- client/js/widgets/widget.js
#1051 stumbled onto a constellation where the order of applying delta changes leads to a crash. This PR makes sure to apply all other changes first before removing widgets.
> fix crash when applying delta

- server/pcioimport.mjs
@mousewax provided a PCIO file that could not be imported. This fixes the problem.
> fix crash when importing PCIO RECALL_CARDS

- client/js/tracing.js
- config.template.json
- server/player.mjs
- server/room.mjs
This PR changes trace mode (F9) to stay enabled after reloading the room.
> keep tracing enabled

- .gitconfig
This update adds one new game and fixes issues in 4 others that were recently uploaded as well as fixing issues in 2 tutorials.
- Forces of Nature. New game similar to Elements, by LawDawg.
- Starship pyramids. Changed pieces so they only rotate left and right (not up and down).
- Mahjong. Added button to display everything remaining in the hand.
- Hearts. Fixed issue with piles in some trick holders. Added reset button. Only displays done passing button when correct number of cards have been passed.  Added option to change number of cards passed from 0 to n.  Take trick button only shows up for player who won the trick.
- Yoink. Fixed 2 automatic scoring problems.  Added a manual turn button in case turns get out of synch.  Fixed problem when pressing "cancel" on the …
> Add Forces of Nature, fix other files

- client/css/jsonedit.css
> Increase JSON Editor Pane Width

- client/js/jsonedit.js
> Use separate tags for widget defaults per-type.

- client/css/overlays/players.css
Resolves part of #249.  Does not address what happens over the hand.  That will take some more sophisticated coding that I may or may not be able to do.
> Change user cursor circle to outline

- client/js/jsonedit.js
Now the JSON editor provides correct prompts for grid elements.
> Add grid commands to JSON editor.

- client/js/jsonedit.js
> Round coordinates in multidistribute.

- client/css/jsonedit.css
- client/js/editmode.js
- client/js/jsonedit.js
- client/js/main.js
- client/js/widgets/seat.js
- client/js/widgets/widget.js
Several performance improvements to the selection highlighting in the JSON editor, the tree rendering and the hovered widgets detection.
It also improves the performance of the properties `onlyVisibleForSeat` and `linkedToSeat`.
And it adds a timer to the routine debug output so game designers can try to optimize their routine performance as well:
> Performance improvements

- client/js/editmode.js
Fixes #1322 
Note that this increments the *last* set of capital letters. Is that what's desired? (For example, 'AxxxY' -> 'AxxxZ', not 'BxxxY'.) If not, I think the RE needs to be changed to `/^(.*?)([A-Z]+)([^A-Z].*)?$/`.
> Now capital letters are incremented using Excel style.

- client/js/jsonedit.js
Addresses #1273. I think this is the solution we agreed on; highlighting will never really work properly on pieces like the pawns.
> Add user control of widget highlighting in JSON editor.

- server.mjs
I thought it would already work but apparently browsers ask with an `OPTIONS` request before actually `PUT`ting.
> add OPTIONS to /state/ in order to allow PUT from different origins

- client/js/jsonedit.js
> Remember to update/highlight selected widgets in multiselect case.

- client/css/jsonedit.css
- client/js/jsonedit.js
- client/room.html
@Ingegneus Resolves #1372 
The open and close buttons seem sluggish at times to me, which makes no sense since all they do is toggle a classlist element.
> Change debug output to be a button.

- client/js/editmode.js
> always send update for deleted properties

- client/js/serverstate.js
I made a search for some widget that are not frequently cited in the code (canvas, timer, spinner) and this seem the to the only list with a mistake
> fixes mistake inserverstate.js

- client/js/jsonedit.js
currently, the line break is "* "
"NULL", "TRUE" and "FALSE" should return the boolean, and number strings are converted to float
context is '^deck ↦ cardTypes'
> CSV support for decks

- server/room.mjs
PR #1223 does not migrate assets to the new public library format correctly.
> fixed asset migration

- client/js/jsonedit.js
This was just a quick idea I had. Do you like it?
> split type specific commands from widget commands in JSON editor

- client/js/main.js
- tests/testcafe/editor.js
- tests/testcafe/publiclibrary.js
Please see the Wikipedia entry [Fisher-Yates Shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) for its benefits.
This implementation also consumes less memory (integer rather than float; no need to duplicate widgets).
> Use Fisher-Yates shuffle instead

- tests/testcafe/editor.js
Fixes #1585 by setting the window size in the editor test.
> set window size in create game test

- library/tutorials/Functions - INPUT/0.json
See if I can get a quick approval on this one.  I just added one button to the INPUT tutorial.  Should have been part of #1625, but I forgot about it.
> Tutorial - Update `INPUT` with palette

- README.md
> Update Readme with valid Discord link

- assets/fonts/symbols.json
Fixes #1626 after #1541 broke it.
> fixed symbol picker

- library/games/Universal/0.json
No idea why it is missing. LawDawg, any reason?
> update similar to name of Universal

- package-lock.json
- package.json
Another round of updates. Will play-test on the beta server in the next days.
> updated dependecies

- library/games/Knaves/0.json
- library/games/Wordy/0.json
Fix some language metadata entries in the public library:
Wordy also got a globalUpdateRoutine and fixed an issue with tiles when leaving the hand.
> Update Public Library Language Metadata

- library/games/Fantasy Wars/0.json
- library/games/Fantasy Wars/1.json
fixed some typos in the 4 player version of fantasy wars
> fixed fantasy wars  4 player version

- client/js/widgets/widget.js
This PR copies any textarea value of the original widgets to the enlarged widgets.
> show label text when enlarged

- library/games/Alphabet Soup/0.json
> PL Fix Alphabet Soup

- library/games/Tantrums/0.json
Three pieces in seat 1 were not visible.  This PR fixes that.
> PL Fix Tantrums

- client/js/main.js
- client/room.html
- config.template.json
- server/minify.mjs
Currently only used for the title tag.
> added `serverName` to config

- server/room.mjs
Adding the first variant already tried to save all assets from all variants but then could not read the second file.
> fixed adding games with multiple variants to the public library

- client/room.html
- package-lock.json
- package.json
- server.mjs
- server/minify.mjs
- tests/testcafe/editor.js
This PR checks the user agent against a list of known bots. The idea is to send the normal room HTML to browsers and Open Graph metadata to bots so we can change link previews without requiring to modify the room HTML on every access.
> added Open Graph support

- client/js/mousehandling.js
> Fix so player cannot drag widgets off screen in play mode

- client/js/overlays/states.js
The ID contains slashes which were not escaped in the download link. This is part of #1847 but it does not look like that one will be merged any time soon.
> fixed download of Chinese Chess

- client/js/widgets/widget.js
- library/tutorials/Functions - INPUT/0.json
If you make "cancelButtonText" and "cancelButtonIcon" null, then the cancel button is not displayed.
> Allow cancel button on INPUT overlay to be hidden

- library/games/Shattered Dominion/0.json
Fixes inherited colors in pawns.
> Update PL Shattered Dominion

- client/js/jsonedit.js
- client/js/widgets/widget.js
- library/tutorials/Functions - INPUT/0.json
- library/tutorials/Functions - INPUT/1.json
Now you can define a regular expression to match an `INPUT` string against and use `regexHint` to tell the player about it if the input does not match it.
> added `regex` to `INPUT.string`

- client/js/overlays/states.js
- client/room.html
As discussed on Discord. Please do a few tests on different viewport sizes to see if the layout breaks anywhere.
> added Designer to similar game metadata

- client/css/jsonedit.css
- client/editor.html
- client/js/jsonedit.js
Now on the overlay that shows the widgets under the cursor.
> added back mouse coordinates to editor

- library/games/WORD STAX/0.json
> PL Word Stax Fix Language Dash

- library/games/Bear Necessities/0.json
> PL Update Bear Necessities - Fix typo in meta data description

- client/js/main.js
- client/js/serverstate.js
- client/js/widgets/widget.js
This should fix #2000, #2001, #2002, #2003 and #2004 which were only three separate but related problems.
> fixed several issues with INPUT and ESC

- client/js/overlays/states.js
Fixes #2031. A broken CSS selector left over from #1908.
> fixed Unlink button in game menu

- library/games/Steam Power/0.json
An update by Jonathan Cox that makes the board clean when first loading it.
> Steam Power: board cleared before start

- library/games/Great Greece/0.json
Public library game Great Greece: Correct the card count (one card was duplicated and another was missing)
> PL Great Greece: Replace incorrectly-duplicated card

- library/games/Konigrufen/0.json
Fix position issues with open hands.
Add cursor visibility settings
> Public Library - Update Konigrufen

- library/games/Creation/0.json
Add additional cards/tiles to match what is in the box.  Mistake based on a misprint in the English rules
> Public Library - Update Creation

- library/games/Spring Cleaning/0.json
> PL - Update Spring Cleaning

- library/games/Great Greece/0.json
Fix setup problem where oracles not randomly distributed
> Public Library - Update Great Greece

- client/js/editor/sidebar/toolbox.js
This adds a powerful but very simple search and replace feature to the toolbox of the editor.
This should be put somewhere else and be more polished but I do not feel like working on this for hours right now.
> simple search and replace in the editor

- client/js/widgets/widget.js
Fixes #2172 by implementing a check for an undefined "unskipped" variable.
> Fix skipTurn bug when no seats are available to have the turn set

- client/js/widgets/canvas.js
This is a critical fix I did as part of #1953 but I do not think that that PR will get merged anytime soon.
> fixed missing awaits in canvas

- client/js/editor/toolbarButton.js
> fixed dimming of editor toolbar buttons based on selection

- client/js/editor/sidebar/properties.js
- client/js/main.js
> removed duplicate function `shuffleArray`

- client/js/editor/toolbar/fullscreen.js
> fixed that the editor fullscreen button would sometimes show the wrong state

- library/games/Runway Roll/0.json
I have been working on this on and off for weeks now. This is the first time where the base game should be complete. The How To Play section took quite some time.
I will probably still improve it because I am actively playing this daily. It is awesome.
> Public Library - Add Runway Roll

- client/css/jsonedit.css
- client/js/jsonedit.js
This is still WIP but as long as no lines wrap, it should already be pretty nice. Ran out of time for now but wanted to show the current state. Fixes #2165 when done.
> added line numbers to JSON editor

- client/js/editor/dragbuttons/spacing.js
Fixes #2235. That was way easier than expected. Simple typo.
> fixed spacing tool behavior for vertically aligned widgets

- client/js/jsonedit.js
> fixed that newly added widgets would not be displayed in JSON editor

- client/js/jsonedit.js
> multi-selection mode can now be used to set objects to properties

- client/js/widgets/dice.js
Fixes #2066. The code was only looking at `svgReplaces` on each face, not on the widget itself.
> fixed that dice would not update when its `svgReplaces` would require it

- client/js/jsonedit.js
Fixes #2240. Was broken by #2229.
> fixed open parent, open deck and open widget by id

- server/room.mjs
> fixed that PCIO importer would not use filename as name

- server/pcioimport.mjs
Fixes #2151. See commit messages. The randomizer is probably a different PCIO file posted in https://boardgamegeek.com/thread/3224205/article/44567855#44567855 which seems to work just fine.
Putting the tokens onto the cards is a lot prettier in PCIO than in VTT but it is close enough, I guess. We gotta overhaul holders at some point...
It feels pretty weird to simply change the default of FLIP like that. But to prove that the default used to be different, we would need old PCIO files where we are sure about the old behavior...
> PCIO importer improvements

- client/js/editor/dragButton.js
- client/js/jsonedit.js
Fixes #2247. Looks like this was never a thing...
> SHIFT+F<X> now deselects the widget if it was already selected

- client/js/editor/dragButton.js
Fixes #2238. Can probably be simplified and faster but ChatGPT made it work...
> ensure that the drag toolbar cannot be dragged off screen

- client/js/compute.js
- library/tutorials/Arrays/0.json
- library/tutorials/Arrays/1.json
- library/tutorials/Arrays/2.json
- library/tutorials/Arrays/3.json
- library/tutorials/Arrays/4.json
- library/tutorials/Arrays/5.json
Takes an array, returns the sum of its elements. Should this be more fancy to handle values of an object or anything other than numbers in the array?
> added compute function `sum`

- library/games/Property Tycoon/0.json
Still fixing seat 6 issues.  Missing + and - buttons are now displayed.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2295/pr-test (or any other room on that server)
> Public Library - Fix Property Tycoon

- library/games/Runway Roll/0.json
See commit messages. Those little indicators are a pretty hard to hit target, especially on phones. So now they move automatically.
> Public Library - light automation for Runway Roll

- library/games/Mauer/0.json
I fixed it at some point but apparently not in the version that got added to the library.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2296/pr-test (or any other room on that server)
> Public Library - fix turn order in Mauer

- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .vscode/launch.json
First test. Goal is that VTT starts automatically when opening a Codespace.
> added Codespaces support

- client/js/editmode.js
It doesn't matter for buttons because they have it set anyway.
But it shouldn't be unnecessary _and_ invalid. :grin:
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2298/pr-test (or any other room on that server)
> fixed no-repeat typo in hex preset

- client/js/widgets/widget.js
Fixes #2117. It was getting annoying while working on #2258.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2304/pr-test (or any other room on that server)
> inherit properties again when overriding ones are removed

- library/games/Guan Dan/0.json
Fixed initial state bugs
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2335/pr-test (or any other room on that server)
> PL-Update-GuanDan

- library/games/Searching for Sasquatch/0.json
Fixes problem that sitting in seat does not update playerName variable.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2364/pr-test (or any other room on that server)
> PL Searching for Sasquatch - Fix Broken Seat Routines

- client/css/overlays/states.css
Fixes #2355
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2359/pr-test (or any other room on that server)
> Fix star number location

- client/js/jsonedit.js
Fixes #2366. It should instead now show a popup.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2370/pr-test (or any other room on that server)
> added error handling to the Copy State JSON editor button

- client/css/overlays/states.css
- client/js/domhelpers.js
- client/js/jsonedit.js
- client/js/main.js
- client/js/overlays/welcome.js
Fixes #2365. Reverts #2359. Caused by #2324.
The emoji replacement code was updated and caused another span to be inserted which made the CSS rules not match anymore.
This PR now only inserts a span when there actually were emojis. The star count should never contain any.
---
The last commit was intended for a new PR but oh well. It fixes that emojis in the game name would not be replaced by images in the share game overlay.
This also fixes that you could insert arbitrary HTML by using emojis in non-HTML game metadata.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2368/pr-test (or any other room on that server)
> fixed star number

- client/js/tracing.js
- client/room.html
Fixes #2358. You can see the error now if you want to.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2371/pr-test (or any other room on that server)
> added technical details to the client crash overlay

- client/js/editor/sidebar/properties.js
You can select a Card Design, deselect it and click Add To Game. Crash.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2388/pr-test (or any other room on that server)
> fixed crash in deck generator

- client/js/jsonedit.js
The button looks for CSS variables but could not handle an object in the `css` property.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2389/pr-test (or any other room on that server)
> fixed crash when adding a new cardType

- client/js/widgets/widget.js
Fixes 2397.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2403/pr-test (or any other room on that server)
> fixed transitions

- client/css/layout.css
Fixes #2306.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2416/pr-test (or any other room on that server)
> Fix pile overlay color in darkmode

- client/js/jsonedit.js
Fixes #2309
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2415/pr-test (or any other room on that server)
> Give focus to first JSON command option

- client/js/editor/sidebar/properties.js
Fixes #2423
The problem was the class "card" is already defined in css elsewhere.  So I just changed references to class "card" to class "cards."
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2424/pr-test (or any other room on that server)
> Fix deck generator dark mode color problem

- library/games/Guan Dan/0.json
Various bug fixes.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2427/pr-test (or any other room on that server)
> Public Library - Update Guan Dan

- client/css/fonts.css
Fixes #2437. Please test. :)
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2438/pr-test (or any other room on that server)
> fixed symbol picker filter for new nofill icons

- client/css/widgets/holder.css
Fixes #2442. Not the most elegant because I just copied over a bunch of CSS properties but I think this is the safest solution..
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2443/pr-test (or any other room on that server)
> fixed card border with `showInactiveFaceToSeat`

- library/games/Everything Must Go_/0.json
Fix seats and turns
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2451/pr-test (or any other room on that server)
> Public Library - Update Everything Must Go!

- library/games/Card Constructor/0.json
Enhanced automation in setup and round buttons.  Metadata update to reflect changes.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2465/pr-test (or any other room on that server)
> Public Library - Card Constructor Updates

- library/games/Going Nuts/0.json
Fix tile swap.  Dragging 1 card into swap holder now correctly gives 3 tiles.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2482/pr-test (or any other room on that server)
> Public Library - Update Going Nuts

- library/games/Mauer/0.json
The resetProperties was broken after the RESET function was added.  This seems to be a one-off that only impacted this game and not a problem with other games that used the old loopRoutine.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2491/pr-test (or any other room on that server)
> Public Library - Update Mauer

- client/js/editor/sidebar/assets.js
- client/js/jsonedit.js
- client/js/widgets/card.js
If a face in `faceTemplates` does not contain an `objects` entry (or it is not an array), the client crashes.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2493/pr-test (or any other room on that server)
> fixed crash for card face without objects

- library/games/Runway Roll/0.json
This PR adds the Ready To Play scenarios to the game. It also finally moves one reroll token off the altitude track for red and black scenarios and it implements the HND rebalance.
I will probably add the Print And Play scenarios tomorrow. The expansion will probably be its own PR.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2499/pr-test (or any other room on that server)
> Public Library - More scenarios for Runway Roll

- client/js/jsonedit.js
I knew I wanted to implement this for a while but when I was working on Runway Roll, it was driving me crazy enough to do it.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2503/pr-test (or any other room on that server)
> save cursor position in editor per widget

- library/games/From now we float/0.json
- Enhanced end turn script for the F ability
- Card transitions
- Force next turn button
- Updates to metadata reflecting the above changes
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2508/pr-test (or any other room on that server)
> PL-Update From now we float

- library/games/Patolli/0.json
Fix broken board layer
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2600/pr-test (or any other room on that server)
> Public Library - Update Patolli

- client/js/jsonedit.js
Fixes #2259. Fixes #2640. Fixes #2639.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2641/pr-test (or any other room on that server)
> fixed editor context for icon and multi-selection

- client/css/layout.css
Fixes #2636.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2642/pr-test (or any other room on that server)
> fixed showing hidden widgets without JSON panel

- validator/validate_gamefile.js
Using both does not make sense. Probably an accident.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2644/pr-test (or any other room on that server)
> validator: check simultaneous use of operand1 and condition in IF
