- .editorconfig
- .gitignore
- client/js/main.js
- client/js/widgets/button.js
1. Put focus on the Go button when user input overlay is presented. This enables the user to press the enter key without having to move their mouse.
2. Support a default value for INPUT type `checkbox`.
These changes also:
* establish an editorconfig file
* git ignore tgz files created by `npm pack`
Corresponding updates for the wiki (see [this gist](https://gist.github.com/larrybotha/10650410) for how to bring in the changes using git cli):
> User input checkbox defaults and Go button focus

- client/js/editmode.js
This is not as easy as it sounds because of parents but I think this solution should work in most cases.
After adding the new widget it checks if the widget has an explicit position set and if it does and its absolute coordinate is `x>1500` or `y>900`, it gets moved 40px to the left/top.
> changed duplicate button to offset to the left at the edge (fixes #52)

- client/js/widgets/holder.js
- client/js/widgets/pile.js
I hope I didn't forget an edge case but now onEnter and onLeave should be applied to all children of piles.
Please test this a bit.
> fixed that onEnter/onLeave would not handle piles correctly (fixes #82)

- client/js/widgets/holder.js
The fix of onEnter/onLeave broke the alignement of cards inside piles. This happens pretty much every time a reset button is pressed.
I only did very basic tests where the problem seems to be fixed. Please test some more stuff in tutorials and games.
> fixed pile alignment after RECALL

- client/js/widgets/button.js
After each `SELECT` operation every pile in the resulting collection will be replaced by all its children.
This will probably break a few rooms out there but I'm pretty sure everyone affected will love the change.
> SELECT now resolves piles

- client/js/editmode.js
> prevent button "All -1" in deck editor to set card counts below 0 (fixes #100)

- client/js/widgets/button.js
Using SET with a parent that doesn't exist throws a Javascript error. This catches the attempt in SET.
There are still many ways to set an invalid parent but I think this covers 90% of real life use cases.
> prevent SET from setting a non-existent parent (fixes #110)

- server.mjs
Trying to download an unknown state from a room currently crashes the server. This PR catches any exceptions in the downloadState function.
> added errorhandling to state downloads

- server.mjs
- server/room.mjs
Issue #157 shows that server crashes can happen that don't trigger the error handler that takes care of saving rooms to the filesystem.
While the goal is obviously that the server never crashes, this PR adds a failsafe that saves any active rooms once per minute.
> autosave rooms once per minute

- client/css/layout.css
closes #177 
This defaults all widgets to `white-space: pre-wrap`. `white-space: pre-line` would also preserve newline characters but collapse horizontal white space characters. Since all widget DOM elements are generated by the js code there shouldn't be any extra whitespace in any of them so `white-space: pre-wrap` should be fine.
> preserve white space in widget text

- server/room.mjs
When removing the update link, it will now download the current state of that link to a static file like any other variant.
This also _finally_ introduced a `variantFilename` to `room.mjs` so the structure and character checking isn't duplicated five times.
So please test adding/loading/removing variants/states a bunch.
> fixed that removing an update link from a variant would lead to room resets (fixes #169)

- client/js/widgets/button.js
fixes #162 
Test case loaded to room. To reset the test case, choose "GET missing property bug" from the "Development" game in the games list.
Clicking button updates label to "Success!" after adding/incrementing a "clickCount" property.
> handle property missing in GET first

- server/fileloader.mjs
Pretty much the only reason there's a limit is so that people don't host pirated movies or whatever on the server.
Since some games already hit the 2MB limit, we should increase it.
> increased the JSON file size limit to 20MB

- client/js/widgets/button.js
This PR adds extra functionality to applyVariables:
1. When using `property` instead of `variable`, you can specify the widget ID and one the widget's state properties (e.g. x, y , z, id, etc.) and apply that value to the parameter. 
2. Instead of stating a widget ID, you can refer to the ID of the clicked button with "this"
3. When using `template` instead of `variable`, you can use variable names as placeholders with curly braces in a text, which will then be replaced by the variables value (mostly suitable for LABEL operations)
```
"applyVariables": [
{
"property": "widgetID.x",
"parameter": "x"
},
{
"property": "this.y",
"parameter": "y"
},
{
"template": "name: {playerName}",
"parameter": "value"
}
]
```
EDIT:
I've decided against the "." in the property. Now property is automatically …
> applyVariables with property and template functionality

- client/css/jsonedit.css
- client/js/jsonedit.js
- client/js/main.js
- client/js/mousehandling.js
- client/js/serverstate.js
- client/js/widgets/widget.js
- client/room.html
- server/minify.mjs
Yesterday evening I had a few ideas and was thinking: what would the editor look like that I would want to use?
It is inspired by the discussion we had last meeting about #135. This is meant for power users who edit JSON manually on the PC with a big screen. It will **definitely not** replace any of the other editors (well, the JSON one maybe).
I have **a lot** more ideas and plans for this but now is the first time where it might be useful.
The basic ideas:
- JSON editing front and center. Complete browser height to have as much visible as possible.
- **Many** context-sensitive hotkeys using `CTRL` and `SHIFT` to modify the JSON and the widgets. Most of them visible on the screen.
- The room itself should always be visible and playable.
Press `CTRL+J` to toggle it. Then `CTRL`-click on a …
> added a new keyboard focused JSON editor

- client/js/main.js
- client/js/widgets/basicwidget.js
- client/js/widgets/card.js
I've been wanting to have this since the beginning. We were talking about proper game pieces and `currentColor`. So now this replaces the `currentColor` in an SVG by the `color` attribute of the BasicWidget:
```JSON
{
"image": "/assets/1351556175_475",
"svgReplaces": {
"currentColor": "color"
},
"color": "darkgreen"
}
```
This feature is also incredibly useful and powerful for card decks so I also added `svgReplaces` to card face objects:
```JSON
{
"type": "deck",
"cardTypes": {
"blue": {
"color": "blue"
},
"red": {
"color": "red"
}
},
"faceTemplates": [
{
"objects": [
{
"type": "image",
"x": 0,
"y": 0,
"width": 50,
"height": 50,
"valueType": "static",
"value": "/assets/1351556175_475",
"svgReplaces": {
"currentColor": "color"
}
}
],
"border": false,
"radius": 8
}
]
}
```
> added svgReplaces to BasicWidget and card face objects

- server/room.mjs
When deleting states and/or variants from a room, it now actually removes the files from the save directory. And when unloading a room, it also removes the room file itself if it doesn't contain any states or widgets.
You can't see if the test server actually deletes stuff but please do a few tests that it doesn't delete stuff it shouldn't.
Note that the variant can be visible in the game overlay but the file might be gone. You'll only know when you try to actually load it.
> rooms cleanup unused files on the server

- server/connection.mjs
There are 2 JSON.Parses currently in the code that have no form of exception handling. One is client facing, so a malformed JSON sent to the server could cause it to crash. The other is used internally, but in parts of the code that may change often.
> added try-except around client message jsons

- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
- client/js/widgets/spinner.js
- client/js/widgets/widget.js
This PR adds a clickable property to BasicWidgets, Cards, Spinners and Buttons. It defaults to true, and disables the widget's click functionality when set to false. This is mostly useful in context of holders and the onLeave/onEnter feature, allowing you to disable card flips once a card is moved into a holder. It may also be useful fur buttons or spinners, so I just added it to all clickable widgets.
> Clickable property

- client/js/serverstate.js
Pretty much the same as #223 but that one doesn't pass the tests.
This should really be merged ASAP though because it's affecting some users.
> fixed that jeApplyDelta was called even when the new JSON editor was not enabled

- .gitignore
- server.mjs
Issue #157 is caused by the server process running out of memory. This PR adds a new URL /heapsnapshot that generates a memory snapshot so I can look at the internals.
The snapshot is stored on the server filesystem as to not leak sensitive information.
> added the possibility to get memory dumps

- client/js/mousehandling.js
- client/js/widgets/widget.js
Resolves #230. This makes the JSON editor respect `movable` and `movableInEdit` properties. When not zoomed out it also makes the JSON editor respect the room boundaries for moves.
> JSON editor respects movable properties

- .gitignore
- client/js/editmode.js
- server.mjs
Default counters are almost unusable on mobile devices because the plus and minus buttons sit within the overly large label text area.  This change shrinks the size of the text area box and slightly repositions the plus and minus buttons in relationship to the new box.  Values -999 to 999 still fit.  See screenshot for example of change; new default counter is on top and the original one is on the bottom.  The other change was needed to slightly reposition the default counter in the add widget menu to account for the change in size.
> Improve default counters for mobile devices

- client/js/mousehandling.js
Adds moveTarget. moveTarget is the mouse target if the widget is movable in current context, Otherwise it is the nearest ancestor widget that is movable. If no movable ancestor is found moveTarget is null. Fixes #184
> Move parent widget if not movable

- client/js/domhelpers.js
- client/js/jsonedit.js
Only for JSONeditor:
Fixed issue when selecting asset URL with surrounding quotes, it was replaced with new ID but without surrounding quotes.
For basicWidgets and Cards, you can now position the cursor on the image value to get the "upload a different asset" context action, instead of having to select the entire URL.
Added check for successful upload of asset before replacing the image value.
Fixed setting of `multiple` attribute in the file input field (undefined callback function would still set the attribute and thereby allow users to select multiple files despite no existing handler).
> fixed uploadAsset

- client/js/widgets/button.js
Added properties: {} to the list of defaults to avoid crash if properties is not present.
> Fix bug in CLONE

- package.json
This adds the ability to run a local VTT in debug mode (uncompressed JS) across environments. Without this, you have to run it with "SET NOCOMPRESS=1" on Windows, but even then I only got it to work with Chrome. I hope this change doesn't affect environments other than Windows.
> npm run debug across environments

- .gitpod.yml
https://gitpod.io/#https://github.com/ArnoldSmith86/virtualtabletop/pull/283 should start the built in test browser to the `/test` room now. Before it just opened `/` and in turn created a new room every time it was reloaded.
> changed the GitPod config so it always opens the same room (test)

- client/js/jsonedit.js
- client/js/widgets/button.js
- client/js/widgets/label.js
- client/js/widgets/widget.js
LABEL also works on collections and can also change the label of Buttons and Basic Widgets
COUNT can also use a `holder` parameter to count any holder's direct children (matching `dropTarget` and resolving piles).
It initially also counted any other widgets it finds in the holder, but as that would make it inconsistent with other button operations, I've removed that part.
It also contains simple fixes to json editor.
Resolves #63
> Improvements to LABEL and COUNT

- client/js/jsonedit.js
- client/js/widgets/button.js
SET now uses the operations from COMPUTE for the `relation` parameter. The property value is mapped to `operand1` and the value to `operand2`. There's no breaking changes, but you can now do stuff like 
```
{
"func": "SET",
"collection": "thisButton",
"property": "x",
"relation": "pow",
"value": 2
}
```
Other changes:
* added "random" to operations
* added "=" to operations, which simply sets a property to the given value (no computation, for backward compatibility with SET)
Resolves #269 and #270
> SET uses compute functions

- client/js/widgets/button.js
I found that JavaScript does not prevent duplicate array entries in case of an array of objects. So, I had to add some lines so that widgets are ignored when their id is already in the collection.
Resolves #277
> Fix for duplicate ID in selected collection

- client/js/widgets/button.js
The new code that prevented duplicates in a collection also looked at the widgets that were in the collection _before_ the `SELECT` even if it used `mode:set`.
> fixed that SELECT would not include widgets that were in the collection previously

- client/js/widgets/button.js
The introduction of `compute` in `SET` also introduced the check that the result is numeric. So `null` was replaced by `0` which breaks everything if that's what you set a widget's `parent` to.
> fixed that COMPUTE wouldn't allow setting stuff to null

- .gitpod.yml
- package-lock.json
- package.json
This should take care of the fact that after every `npm install` there are changes to the package*.json files.
> update package-lock.json version in hopes that Dependabot now respects it

- client/js/editmode.js
- client/js/jsonedit.js
The code for creating a widget ID, in `addWidgetLocal`, was removed to its own function. All four places in the client code where a random widget ID was created now call that function (three in editmode.js, one in jsonedit.js).
The other places in the client code where `Math.random` is called are:
1. Determining a player name in players.js. Apparently there is no convenient client-available list of all players, so I've left that one alone. The odds of a conflict are relatively low, since there will likely be no more than 10 players and the random number has 3 digits.
2. In pile.js and button.js, to do a shuffle. Conflicts here likely happen regularly, and they don't matter since JavaScript has an algorithm for resolving siblings with the same z-value. Left alone.
3. Places where …
> Ensure uniqueness of widget IDs (fixes #289)

- client/css/widgets/card.css
This is the fix for #240 @96LawDawg proposed in #241.
The problem is that it hides parts of child widgets that are not overlapping the card.
But I think it's completely reasonable to enforce that nothing sticks out of the card.
Please test this in the browsers that currently show the problem.
> added overflow:hidden to cards again

- client/js/jsonedit.js
This adds a button on the top row to duplicate the currently selected widget. The new widget will be added at the very same position, so it won't easily be noticable, but I don't think that's a problem for people working with the JSON editor anyhow.
I've given this function the hotkey Ctrl+Shift+D, which was used by `remove property`, but I think the top row buttons should all have a fixed hotkey and I couldn't think of any other suitable one (Ctrl+Shift+C for copy/clone cannot be used on Windows).
Resolves #212
> add duplicateWidget function to JSON editor

- client/room.html
I've tested [ArnoldSmith86 suggestion](https://github.com/ArnoldSmith86/virtualtabletop/pull/273#pullrequestreview-616219277) for an alternative button fix and found that it works similar, but not identical and I'm not sure which is better.
On my iPhone, PR #273 shows the Go and Cancel buttons as short buttons, not in the wide button styles used in pile actions. Also, I had the option to "Open" or submit the form via the iPhone keyboard.
In this PR, the buttons use the same style as the pile actions (although at first the buttons didn't render correctly) and the iPhone keyboard does not show an "Open" option. To submit the form, you have to click the Go button.
I'm not sure which alternative is better, which is why I'm opening this for others to test as well.
Resolves #271
> fix Go button (alternative)

- client/css/widgets/basicwidget.css
- client/css/widgets/label.css
by adding the editmode-colored 3 pixel border in edit mode. Requires adding a drop shadow and changing box-sizing in edit mode as well to avoid apparent widget movement.
Replaces https://github.com/ArnoldSmith86/virtualtabletop/pull/264
> Fix visibility of label and basic widgets

- client/components/baseEditOverlay.js
- client/components/deckEditor.js
- client/components/loadComponents.js
- client/js/editmode.js
- client/js/main.js
- client/js/serverstate.js
- client/room.html
- package-lock.json
- server/minify.mjs
Keeping the deck editor visually + functionally exactly the same, but using Vue.js as the underlying framework.
Serves as a proof of concept for future UI component implementation.
Deck editor revamp will happen in another branch.
> Migrate Edit Overlay to Vue.js

- client/js/jsonedit.js
The browser crashes everytime I Ctrl-Click a widget in json Editor mode. I think I've found and fixed the problem, but maybe someone else can confirm.
> fix new json Editor overlay

- client/js/widgets/card.js
If you set the property `deck` to an existing widget which is not actually a `Deck`, the client would continually crash.
I added a check for that which doesn't trigger for every edge case of how to get there but it should break the loop and let you know what's wrong.
> cards now check if their supplied deck is actually a deck

- client/js/widgets/button.js
Until we added all COMPUTE relations to SET (PR #279), people could use SET with `==` to set a property to the given value, although `==` is a comparator, not an assignment operator.
Non-programmers frequently get confused about when to use `==` instead of `=`, so this PR aims to fix this issue by allowing for `==` in SET but giving a warning.
This change means that `==` cannot be used as a comparator in SET, only in COMPUTE.
> fix issue with = vs == in relation

- client/js/jsonedit.js
Error checking in the JSON editor commands was all over the place and it crashed pretty often while editing the text.
I refactored the error checking to be global (not in each command) so hopefully there are less problems now.
I also added the "go to error" command again after @larkob unintentionally removed it because it was part of the superfluous "apply changes" command.
> crash fixes for JSON editor + "go to error" command

- client/components/baseEditOverlay.js
- client/js/editmode.js
- client/js/jsonedit.js
The Vue transition removed a check that only applied the UI element values (for example the "Transparent" checkbox of the holder) if you didn't edit the JSON directly. Without that check the value of the checkbox gets applied even if you changed its property in the JSON.
> fixed that you couldn't edit holder classes through JSON anymore

- client/css/jsonedit.css
- client/js/jsonedit.js
- client/js/statemanaged.js
Selecting text from right to left produces the correct context for commands.
Macros are still not incredibly useful but at least they should work again.
If `x`, `y`, `width` or `height` are numeric strings, the `F1` keys now show the correct widgets because the values are converted to numbers by function `p` now.
Explicitly setting `"parent": null` in the widget will no longer trigger the "parent exists" test.
Special HTML characters were not escaped, leading to problems in the JSON editor.
There's now a check that looks if the widget given with property `deck` contains `cardTypes`.
Copying text to the JSON editor now pastes it as plain text using a custom paste event handler so that the browser doesn't insert weird stuff into the contenteditable editor that messes up commands and …
> JSON editor fixes

- client/js/widgets/widget.js
Resolves #345 which needed the addition of COMPUTE operations dealing with decimal numbers. I also added two functions to generate random whole numbers based on the Python equivalent.
The new functions are:
* toFixed: converts a number into a string, rounding the number to keep only the specified amount of decimals
* parseFloat: parses a string and returns a floating point number. It determines if the first character in the specified string is a number. If it is, it parses the string until it reaches the end of the number, and returns the number as a number, not as a string.
* randInt: generates a random integer in a min-max range, including the end points (identical to RANDOM button operation)
* randRange: generates a random integer in a min-max range, excluding the max point. Allows to …
> COMPUTE with toFixed, parseFloat, randint and randrange

- .github/workflows/testcafe.yml
- tests/testcafe/tests.js
This introduces new tests that get executed by GitHub after every commit.
It basically opens a browser somewhere in the cloud, loads some games (and tutorials) from the public library, clicks a few buttons in those games and then checks if the resulting room state is the same as when I wrote the tests.
We'll see if we want to keep these game tests or replace them by dedicated test rooms. I feel like it's a good idea to check the actual games.
This can be expanded quite a lot and can potentially also drag cards around (or play entire games) but for now I would like to gather some experience.
These tests will break every time one of the tested games/tutorials receive an update. For now I will update them manually but we can also automate the process in the future.
> implemented automated game testing using TestCafe

- client/js/connection.js
- server.mjs
- server/connection.mjs
- server/room.mjs
Loading the room state from invalid files or links caused server crashes and all kinds of issues. That should be fixed now. Instead the user receives an "Error loading state." message and the room will be set to an empty room (the game list will stay untouched).
Please see #389 for an explanation of why this currently happens a lot.
> fixed server crash when loading a state from an invalid link

- tests/testcafe/tests.js
Many of these edits were prompted by recent changes allowing for additional customization on buttons for colors and images.
Assets:
- Add example of text and image on same button in universal game symbols; add library image
- Add a new variant of Dice with BicycleIndividual’s completed jumping dice deck
Tutorials:
- Add example of text and image on same button in Button Appearance tutorial 2nd variant
- Fixed an outdated comment in Functions – ROTATE and update appearance of rotate buttons
- Fixed text that did not fit in the button space in Functions – COMPUTE in the 1st variant
- Fixed colors in buttons in SKIP in the 2nd variant
Public Library New:
- Added Don’t Blow Up (similar to Exploding Kittens), Nine Men’s Morris, Quad Line (similar to Connect Four), and Quad Line 3D (similar to …
> Add Don't Blow Up, Nine Men's Morris, Quad Line, many other updates

- client/js/widgets/widget.js
PR #383 accidentally changed the result of a `GET` with `aggregation: sum` on an empty collection from `0` to `undefined` (not setting the variable at all actually). This PR reverts that change and additionally changes the result of `aggregation: array` on an empty collection to be an empty array.
> fixed GET sum of empty collection

- tests/testcafe/tests.js
Another big library update.  Details:
Public Assets:
- Marbles. Added as new library file
- Dice. Added new svg 3d dice to 1st variant
- Functions – IF. Added as new library file tutorial (including a cross-reference to the SKIP tutorial)
- SKIP. Updated a comment about the ‘set’ and ‘add’ modes of SELECT that is no longer relevant after the recent file version update changed the default mode to set. Also made a cross-reference to the IF tutorial
- For all 12 button related tutorials, changed the library image from the default green to the new blue and white style
- Backgammon. Added new game
- Mancala. Added new game
- Chinese Checkers. Added shiny marble variant; added reset button
- Chinese Chess (Xiangqui). Added reset button; changed variant names to …
> Add backgammon, mancala, other updates

- client/js/widgets/widget.js
Until now `grid`s could only define a custom `rotation` which could be used to make something like roads in Catan.
While actually using it, I actually wanted to replace the `image` depending on the rotation because of a 3D perspective effect.
The example on the right of the test room now sets `rotation` and `scale` as an example.
> grids can now set any property on widgets

- client/components/deckEditor.js
- client/js/editmode.js
- client/js/jsonedit.js
- client/js/main.js
- client/js/mousehandling.js
- client/js/serverstate.js
- client/js/statemanaged.js
- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
- client/js/widgets/deck.js
- client/js/widgets/holder.js
- client/js/widgets/label.js
- client/js/widgets/pile.js
- client/js/widgets/spinner.js
- client/js/widgets/widget.js
- tests/client/widget-click.test.js
- tests/client/widget-count.test.js
This was removed from #197 when I realized that every writing access to widget states now has to be async.
This adds new properties to all widgets. They are each an array of operations just like `clickRoutine`:
1. `changeRoutine` which gets called whenever a property of the widget it is in changes. The routine will have preset variables `property`, `oldValue` and `value`.
2. `enterRoutine` which gets called whenever a new child gets added to the widget it is in. The routine will have the preset variable `oldParentID` and the preset collection `child`.
3. `leaveRoutine` which gets called whenever a child gets removed from the widget it is in. The routine will have the preset collection `child`.
In addition you can define changeRoutines for a single property. Just add "ChangeRoutine" to the …
> added changeRoutine, enterRoutine and leaveRoutine

- client/js/domhelpers.js
- client/js/overlays/states.js
- client/room.html
- server.mjs
- server/fileloader.mjs
- server/logging.mjs
- server/pcioimport.mjs
- server/player.mjs
- server/room.mjs
Uploading VTT files failed randomly in the past and using WebSockets there was no way to get information about the current progress.
I now changed it to use XMLHttpRequest which allows for a progress indicator and I think it used base64 before so this already saves some bandwidth.
I used the opportunity to also implement a check that actually opens the vtt file clientside, checks if the assets are already on the server and if more than half of them are, it deletes them from the archive and uploads a newly created file. This should make >90% of all uploads near instant.
> improved game file uploads significantly

- client/js/jsonedit.js
- client/js/statemanaged.js
- client/js/widgets/widget.js
There were a few places in the code that directly accessed `widget.defaults` instead of `widget.getDefaultValue()`. For the most part that is not a problem but for cards default values can be changed in the deck.
The problem that came up is #337: Setting a `x: 100` in `cardDefaults` would not change the behaviour that moving the card to `x: 0` would remove `x` from the card. The system assumed that the default would be `x: 0` but as soon as it is removed it would use the `x: 100` from `cardDefaults`.
> fixed some edge cases with default values

- client/js/serverstate.js
When there are no widgets in the room, the game list overlay is shown automatically to help new users. This leads to confusing behaviour if you actually want to load an empty "game" to clear the room. This PR changes this feature so it only displays the game list _once_ until you reload the page.
> only show games list for an empty room once

- client/css/widgets/card.css
- client/css/widgets/label.css
- client/css/widgets/spinner.css
- client/js/domhelpers.js
- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/card.js
- client/js/widgets/spinner.js
This PR fixes some cases where children would break:
- If properties of a card or spinner changed that triggered a rebuild of their DOM, all their children would disappear.
- If the text of a BasicWidget or button would change, all its children would disappear.
- If a spinner was a child of another spinner it would have the spinning part as another background (because of a CSS rule `.spinner > .spinner` (the spinning part of a spinner also had class `spinner`).
> fixed disappearing children of cards, basicwidgets and buttons

- client/js/jsonedit.js
Modified widget tree display to alphabetize widgets both at the top level and within a parent. This is related to issue #382.
> Fix widget sort ordering in JSON editor tree view

- client/js/statemanaged.js
- client/js/widgets/widget.js
We delete properties when they are set to null, so we should return null for undefined properties.
> Return null for undefined properties

- server/fileupdater.mjs
- server/room.mjs
This PR makes the fileupdater treat the `properties` parameter of the `CLONE` operation as if it was a widget of its own because it just contains a set of properties.
This means that any `*Routine` properties in there will now receive updates as well.
I also noticed that when downloading a state from a room, the downloaded file would have the unchanged JSON from the state but it received the version number from the room itself. This is a very big issue unfortunately because it leads to broken VTT files (and subsequently imports).
> apply fileupdater to CLONE properties and fix version in downloaded states

- tests/testcafe/tests.js
Public Library
- Adedanha. New game by RaphaelAlvez.  Similar to Scattergories.
- Liar's Dice. New game by RaphaelAlvez.
- Blue. Updated after DevGameNight. Added automation to arrows.
- Flora. Updated after DevGameNight. Added 2 automation buttons, discard holders, changed one card color, updated Unicode to images, removed grid from bottom row, and changed onLeave flip behavior.
- changeRoutine.  New. Uses the concept of sliders to illustrate changeRoutine.
- Timer. New. Has basic variant and variant demonstrating how to made a card dealing animation.
- Button appearance. Revised to reflect changes to button color properties from PR #461. Add a basic appearance intro and revised the text only appearance variant.
- Hexagonal cards. Updated “find width” functions to …
> Public library: Add Adedanha, others

- client/js/widgets/canvas.js
This uses `#$%&'()` to encode the repeat length for most colors. The color character is encoded first, then the code for how many times it is repeated if the color occurs for at least 3 pixels in a row (a color occurring only twice in a row the color code simply gets repeated). The characters `*+,-./0` encode the repeat length of the color `0`; but `0` is not always in the encoding. To make `0` mean one `0` the values of the characters used are 1-7 with the highest code point representing the lowest value (no zero is needed, 14 is encoded as 7 ones + 1 seven, 56 is 7 ones + 7 sevens). For the maximum supported canvas size (500x500 - 2500 pixels per region) the maximum possible length of a repeat encoding is 4 characters (7 + 7 x 7 + 7 x 7^2 + 7 x 7^3 = 2800). For a 200x200 canvas (400 …
> place value compression of repeating color values

- client/js/widgets/widget.js
When using `${PROPERTY array}`, it would not create a deep copy of the property but instead return a reference.
This leads to unintended behavior because changing a resulting variable directly changes the property of the widget and at the same time the system does not get notified of the change because it is the _same_ array.
This should be fixed ASAP because the change is a breaking change but IMHO unavoidable.
> fixed that a property variable would not create a copy

- package.json
- tests/testcafe/gitpod.sh
TestCafé works fine in GitPod. It's just that no browser is installed.
This PR adds the command `npm run testcafe-gitpod` which first installs Firefox and then runs `npm run testcafe-firefox-headless`.
> added a command for testcafe in gitpod

- client/js/main.js
- client/js/statemanaged.js
- tests/testcafe/tests.js
- Blue: Fixed layers on a couple of labels.
- Connex: Updated with css rotation animation for game pieces.
- Fantasy Wars. New game by RaphaelAlvez.  Similar to War Chest.
- Hangman. New game by LawDawg.  Portuguese word list by RaphaelAlvez.
- Medieval VNO. Added variant with automation following play on Dev Game Night.
- Reward. Updated with lower z values.
- Tantrums. Updated with css rotation animation for game pieces and replaced Unicode symbols with svg images.
- Button Appearance.  Added on buton on CSS Shapes Variant
- changeRoutine. Optimized all the JSON for dynamic expressions.
- Functions – GET. Added a comment about using dynamic expressions.
- Hexagonal Cards. Fixed typo on button in The Basics variant for calculator of height and width. …
> Add Fantasy Wars, Hangman, other updates

- server/room.mjs
Ensures that new players get a color that is a different hue from the hues of existing player colors.
Easiest way to see new feature is to open an empty test room in a browser and look at the player list. Add additional players by repeatedly opening the room in a Incognito/In Private window then closing the window (in Chrome/Edge all Incognito/In Private windows share local storage, so all must be closed before reopening - did not test in Firefox).
> new players get unique color

- client/css/widgets/label.css
This should fix the issue of labels collapsing or showing a scrollbar when they are empty.  Feel free to close this one and add the change to another PR, I just wanted to be able to test it on the server.
> Fix for collapsing labels

- client/js/jsonedit.js
The context detection in the JSON editor uses the indentation to try to figure out where the cursor is and what commands to display.
When the indentation is not perfect, this does not work reliably.
This PR adds a sanity check to the context detection that makes sure that the detected context actually exists in the widget. If it does not, everything that cannot be found is removed from the context.
> fixed crashes in JSON editor when having inconsistent indentation

- server/fileupdater.mjs
When routines contain entries that are just a string (like the new dynamic expressions), the fileupdater for v3 would crash.
This PR makes it skip any entries that do not have a `func` parameter.
> fixed fileupdater crash for string routine entries

- client/js/jsonedit.js
Just a simple JSON editor command when the cursor is on `x` or `y` that centers the widget in its parent (or the room).
> added command to center widget in parent

- client/js/editmode.js
- client/js/jsonedit.js
You could use the legacy JSON editor to set `parent` to an invalid value which would make the client unresponsive.
This also forced me to fix that the new JSON editor sets properties to `null` instead of removing them.
> improve enforcement of valid parent

- .github/workflows/production-environment.yml
- client/js/jsonedit.js
The minifier crashes for certain changes when `$` characters are in the wrong place. And until now there is no automated test to check if PRs work with the environment used on the production server.
This PR adds a very simple test.
> added an automated test that checks if the server starts with production settings

- client/js/jsonedit.js
- client/js/widgets/widget.js
Fixed to update collections containing the old (renamed) widget.
-----------------------------------
This change makes changing a widget id in `SET` work properly. If the source collection has more than one widget, only the `id` of the first widget in the collection will be modified.
----------------------------------
I have a fix for #415 *almost* working, but there remains what may be a large issue. Suppose you have a holder with a widget inside it, and you first change the id of the holder and then the id of the widget using a `SET`. If you do only the first of these in the routine, everything works properly, but if you try to do both, then both changes get batched up, and when the batch is processed, the child of the holder no longer exists. (I've done this using the same hack as in …
> Added a special case in 'SET' to change the widget id.

- client/js/widgets/widget.js
`FOREACH` backups and restores variables and collections it sets for its `loopRoutine` so that everything is restored to the state it was before the `FOREACH`.
I did not check for `undefined` because I thought it would be fine to just restore it as undefined. But technically there is a slight difference between actually setting a variable to value `undefined` or just not setting it at all.
This PR only restores variables and collections if they were not `undefined` before the `FOREACH`. I did not test this one single bit so please do some testing.
> fixed undefined collections after `FOREACH`

- client/js/jsonedit.js
Whenever the JSON editor updates its text editor because of external changes to the widget, the cursor position would be reset to the beginning.
This PR saves the cursor position before external changes and tries to restore it afterwards. It tries to find the same line and restore the position inside that line because a lot about the widget structure might have changed in the update.
In practice this means it should be possible - after #540 - to edit running timers and - in combination with #539 - it should even be possible for multiple people to edit the same widget (just not the same line) at the same time.
> fixed cursor in JSON editor jumping to the start

- client/js/widgets/widget.js
Setting `property` in `SET` to `null` leads to removal of all widgets in the collection because `null` is used for deletion in the server-client-communication.
This PR converts `property` to a string before setting it so `null` would lead to property `"null"` now.
I feel like we should extent `setDefaults` to enforce types of parameters but I would do that in another PR because this seems like a pretty big issue.
I did not test this at all so please do so.
> convert `property` in `SET` to string before setting

- server/player.mjs
- server/room.mjs
The conflict detection in VTT is responsible for making sure that every client has the same room state. If two clients edit the same widget "at the same time" (so before knowing about the changes by the other client), the server tells the later client that the change was invalid and resends the entire room state.
In general this seems to be working quite well. I am not aware of any instance where two clients diverged from each other.
There have been issues with falsely detected conflicts though. So the conflict resolution was triggered seemingly unnecessarily and one player saw the room blink (state reloaded) and whatever widget they tried to drag got ripped out of their "hand".
When working on JSON editor and timer improvements yesterday, I refined the conflict detection to work on …
> greatly improved conflict detection

- client/js/jsonedit.js
Updated "remove" and "duplicate" commands to work on all currently selected widgets.
Added a command that adds another property to the multi-selection JSON. So for example adding `owner` will add an object containing all owner values of all selected widgets to the multi-selection JSON so you can easily update them for multiple widgets.
Added a "shift" command to any numeric value in the multi-selection that will add the entered value to each widget. This can be used to shift all selected widgets by 100px to the top for example.
> updated JSON editor commands for multi-selection

- tests/testcafe/tests.js
- Moving Walls 3d. New game by Casbuild and ArnoldSmith86.  Similar to 3d Labyrinth.
- Fireworks.  Markers no longer movable, removed pile handle from stacking holders, increased stackOffsetY on discard holders.
- Moving Walls.  New visual elements by Casbuild and fixed game pieces getting lost.
- Undercover. Fixed layer of two cards.
- Undercover Duo. Removed pile handles on top of words.
- Blue. Add automation buttons to empty holders, discard dropped tiles, and improved reset button.
- Arrays.  Activated features enabled by PR 469: in, remove, numericSort.
- Math.  Activated features enabled by PR 469: acos, atan, atan2, asin.
> Add Moving Walls 3D, other updates

- client/js/domhelpers.js
- client/js/jsonedit.js
- client/js/mousehandling.js
As far as I'm concerned this is the biggest feature gap to Ghetto Editor.
Multi-select a few widgets, put the cursor to `x` or `y`, press `align`, select options, press `Go`. All selected widgets will get the same left/top/center/right/bottom coordinate. Even works across different parents.
Multi-select a few widgets, put the cursor to `x` or `y`, press `distribute`. The spacing between all selected widgets is equalized. Even works across different parents.
Because `align` uses it, this also introduces `select` as an `INPUT` type. Something like this:
```
{ label: 'Coordinate', type: 'select', options: [ { value: 0.5, text: 'Center' }, { value: 0, text: 'Top/Left' }, { value: 1, text: 'Bottom/Right'  } ] },
{ label: 'Reference',  type: 'select', options: [ { value: 'First' }, { value: …
```
> added commands to align and distribute widgets

- server/pcioimport.mjs
Internally they are pretty much the same as cards so only minimal importer changes are needed.
So far I only tested it with https://boardgamegeek.com/geeklist/272690/item/8176781#item8176781.
For now it links to the game piece images of PCIO but for most of them we should already have alternatives. I will work on replacing the ones we already have in this PR.
> added importer support for game pieces

- client/js/jsonedit.js
HTML tags were not escaped for the white parts of the text. So when adding HTML to a text property and then removing one of the enclosing quotes, the HTML was actually rendered inside the editor.
> fixed unwanted HTML render in JSON editor

- client/js/widgets/widget.js
- server/fileupdater.mjs
Allows most ASCII printable characters in dynamic expression string literal. fixes #471
Dynamic Expresions wiki page:
~Finally, valid characters for strings are alphanumerics, , (comma), . (period), ( (left parenthesis), ) (right parenthesis), space, _ (underscore), and - (hyphen).~
String literals in dynamic expressions can contain any [printable ASCII character](https://en.wikipedia.org/wiki/ASCII#Printable_characters) (\u0020 to \u007e) except single quote `'` (\u0027), double quote `"` (\u0022), and backslash `\` (\u005c).
> dynamic expression string literal whitelist

- client/js/jsonedit.js
Multi-selection mode in the JSON editor shows a property `widgets` that lists all selected widget IDs. With this PR you can edit that list directly in the text editor to add or remove widgets. It also supports regular expressions so you can add something like `/Player [0-9]+ Holder/` and it will display the values of all matching widgets.
> changing the widgets in the multi-selection mode now retrieves their values

- client/js/widgets/widget.js
It would instead fallback to the `x` and `y` of the cloned widget.
> fixed that `CLONE` did not set `x` or `y` to 0

- client/js/jsonedit.js
I wanted to copy a deck of cards with 96 different cardTypes to a different game. Using the normal edit mode to add every card did not work because it screws up the variables for more complicated decks. So I added a JSON editor command to do it and while I was at it, I added one to remove all cards and I updated the existing ones that only handle a single cardType to show the number of cards on the command button
> added commands to add or remove all cards of a deck

- client/js/serverstate.js
- client/js/statemanaged.js
- client/js/widgets/widget.js
This PR adds the property `globalUpdateRoutine`. It is very similar to the `changeRoutine` but it gets triggered for property changes of other widgets as well.
The main intention behind this is the display of player owned cards for the PCIO seat compatibility (see examples in the test room).
Just like with `changeRoutine`s you can also specify an `ownerGlobalUpdateRoutine` (or any other property) to filter for which property changes the routine will be called. **This is highly recommended to avoid all those `x` and `y` changes you don't care about.**
Contrary to `changeRoutine`s these `globalUpdateRoutine`s do _not_ trigger recursively. So if you change a property inside of the routine, it will not trigger any `globalUpdateRoutine`s. This can be changed easily but I feel like it is not …
> added `globalUpdateRoutine`

- client/js/jsonedit.js
- client/js/widgets/label.js
This is a fix for #660.  It moves the event listener for enter from being applied to the entire window to only being applied to the JSON editor.
Added in fix for #659.  Apparently, the white space (enter) didn't register as different enough to be evaluated as different by !=.
I do believe these two very minor fixes are both working as expected.  I also suspect these are desired changes.  However, this needs a code review to make sure I put the eventListener in the right place, and to make sure the getElementById is required <s>(which I believe it is in this case)</s>.
> Enter in label no longer registered in JSON editor

- client/js/widgets/widget.js
When used in a routine the `INPUT` type `select` would display the dropdown correctly in the overlay but it would not set the selected value to the variable.
> fixed `INPUT` type `select`

- client/js/domhelpers.js
The expression `field.min || 1` would always fallback to `1` if you use a `0`.
> allow 0 as `INPUT` number `min` or `max`

- client/js/editmode.js
- client/js/jsonedit.js
The duplicate command can now create minimal new widgets that use `inheritFrom` to receive nearly all their contents from the source.
This is pretty much the last feature of PR #479. Only a similar command that syncs children to inheriting widgets is still missing but I am not sure what I will do with that one.
> added option "Use inheritFrom" to duplicate command

- client/components/deckEditor.js
- client/js/editmode.js
This is a comparison of how the deck editor and JSON editor in this PR display different types of data.
|  | Deck Editor       | JSON Editor           | Card |
| --------  | ------------------- | --------------------- |--------------------- |
|numbers|123|123|123|
|string numbers|"456"|"456"|456|
|booleans|true|true|true|
|string booleans|"false"|"false"|false|
|empty strings|""|""| |
|strings|this is a string <br>(can also be entered with quotation marks)<br>e.g "this is a string"|"this is a string"|this is a string|
|null values| |(deleted by deck editor)| |
|carriage returns|first line\nsecond line|first line\nsecond line|first line<br>second line|
There are some differences between how the deck editor and JSON editor display data.  It could be made the same, but I thought the …
> Updates to how Deck Editor deals with data

- client/js/widgets/widget.js
Logging routine name was misspelled twice in the `TIMER` code in widgets.js, was untested by test room.
> Fix typos in TIMER code for new debugger.

- client/js/editmode.js
This is to address issue #708
Changes:
- Width and height are converted to float values instead of strings
- Value is taken from the text input rather than the range (slider), so that it will not round values to nearest range (slider) step (currently every 10 px)
- Width and height will not update if a valid number is not entered (numbers and possibly a decimal point)
This only affects tokens, boards, and labels as they are the only widgets that have a width and height in Edit Mode.
> Edit Mode converts width and height to float value

- client/js/widgets/widget.js
- Stops enlarged view from flickering if mouse moves faster than the widget and the mouse moves off of the widget while moving.
- Stops enlarged view from ending if mouse temporarily moves off the screen while a widget is being moved.
- Makes the enlarged view end when mouseleave happens rather than when mouseup happens.  
This addresses issues #31 and #715.
> Stop enlarged from flickering

- client/js/jsonedit.js
This PR should address issue #680 and remove the width and height if those values are already being inherited from either cardDefault or cardType.  So, if it is a value that is overriding the cardDefault or cardType it will remain on the card, but if it is not, then it will be removed.
This is just 1/2 line of code.  All it does it make it so that if they widget is a card and the property is height or width, then it will be treated the same way inherited properties are treated in the JSON editor (not shown if they are not set to a different value).
else if(match[2] == '*' && !o.inheritFrom **&& (o.type != 'card' || (key != 'width\*' && key != 'height\*'))**)
Examples:
http://212.47.248.129:3711/pr-test
> Remove width/height equal to cardDefault/cardType

- client/js/widgets/widget.js
Modified the regular expression to fix #759, at least for trailing whitespace. I decided not to allow leading whitespace, but this is easy as well if people think it's worthwhile.
> Change R.E. for 'var's to allow trailing whitespace.

- client/css/layout.css
- client/js/main.js
Fixed calculations based on VH in mobile WebKit where 100vh extended past the bottom of the browser.
As far as I know this only affects users on iPadOS 15.
Attached images that show the issue and with it fixed.
Problem:
Fixed:
> Adjust for viewport units on mobile

- package-lock.json
- package.json
Public library changes:
- Iago renamed Reversi.  Added automation and alternative rule selection
- Moving Walls 3D.  Added rune cards; fixed dropLimit issue.  There is still an automation error if 2 tokens are on the same space when the arrow buttons are selected to push in the new tile.  Only 1 of the token moves.
- Ninety-Nine. Changes by jade-alarm allow playing of cards from hand just by clicking on them.  Also automation buttons for declaring bid or revealing hand.  Seats and instructions also added.
- Tittle. Increased size of cards.  Made the blue color cards lighter so easier to see on mobile. Moved hand to right side of board and scores to bottom left.  Added +4 and +1 cards to move cards to hand. Made the pile drag handle for the deck of cards not movable to prevent accidental …
> Change Iago to Reversi, other edits

- client/js/widgets/widget.js
This addresses issue #727
It would make it so the JSON below would give you "property1": "new text" instead of "property1": "nullnew text" if the property was a null value previously.
{
"func": "SET",
"property": "property1",
"relation": "+",
"value": "new text",
"collection": "thisButton"
}
Updated to NOT perform a SET if the relationship is `+` and the new value is `null` to prevent results where the property gets set to "old valuenull" instead of remaining "old value".
Game-breaking potential:
- `SET` `+` is mistakenly used on a `null` property instead of `SET` `=`
- The property is then used as a operand in an `IF` statement
- The 'working' behavior is for the property to NOT be equal to what it was just `SET` to be
OR
NOTE: with conditions, currently `SET` `+` `false` to a `null` …
> SET = instead of + if value is null

- client/js/jsonedit.js
- Adds cardType and deck to mouseover in JSON editor.
- Adds cardType to where cardType properties are shown.
I think these changes are convenient, for when someone is editing their cards, and they want to quickly identify the cardType or deck of a card.  However, if they aren't desired parts can be eliminated, or this can be closed.
Test Server: http://212.47.248.129:3737/pr-test
> Adds cardType & deck to mouse over in JSON editor

- client/js/widgets/widget.js
- tests/testcafe/tests.js
Game makers have had some difficulty maintaining the order of cards in games where the order matters. When piles form after a SET, the order of the top two cards currently flip.  This PR would cause that to NOT happen.
Addresses issue described in #741.
If cards are piled 1, 2, 3, 4, 5 and you SET a new parent then the order they will wind up in is 4, 5, 3, 2, 1, always switching the top card (5) and the second card (4).
I do not believe there is any workaround that would be affected by this update.  Any workaround would likely use MOVE or FOREACH.
Can be tested with green and red buttons in pr-test room.
> Retain order of top 2 cards SET to new parent

- client/js/overlays/players.js
- server/room.mjs
I am not sure if I want this or not but I thought I would throw it into a PR.
Rooms used for a longer time tend to accumulate guest players in the player list. This PR hides them if they are inactive (not currently connected).
> hide inactive guests from player list

- client/js/widgets/widget.js
<strike>1. Fix 'return: false' debug information, and make several related changes in CALL processing. The problem was an unnecessary and harmful 'break' after CALL processing. In addition, the return variable and collection were being set even if 'return: false' was specified. </strike>
1. Fix 'return: false' debug information.
2. Fix a minor problem in 'SELECT' debug information reporting.
Test room at http://212.47.248.129:3771/pr-test
> Correctly process 'return: false' in debugging. Fixes #767

- client/js/jsonedit.js
With PR #737 I broke directly editing cards in the JSON editor by using o.cardType instead of state.cardType in the function jeApplyExternalChanges in jsonedit.js.
This simply corrects that error.
Currently on the production server typing in the JSON editor on a card won't update the JSON (because I broke it on accident).  With this PR that functionality is restored.
> Fix editing cards directly in JSON editor

- server.mjs
This PR tells browsers to not ask the server for changes to assets it already has in its cache. The assets have a checksum of their contents in the URL so every change to the content would lead to a new URL anyway.
> improve cacheability of assets

- client/js/jsonedit.js
- client/js/widgets/widget.js
Add 'intersect' and 'remove' as modes for SELECT, and update JSON editor appropriately. Implements #587.
Also (unrelated, but discovered in testing) change the default for `mode` in the JSON editor from `add` to `set`.
If this is merged, the description of `mode` in the discussion of `SELECT` in the Wiki will change to something like:
- mode: set / add / remove / intersect - "set" (the default) replaces any previously stored widgets in _collection_ by the selected widgets. "add" extends _collection_ by the selected widgets. "remove" removes from _collection_ any selected widgets that are in _collection_. Finally, _intersect_ replaces _collection_ by the collection of all widgets that both appear in _collection_ and are selected.
> Add 'intersect' and 'remove' as modes for SELECT

- client/js/widgets/widget.js
Addresses issue descripted in #820.  Prevents an automatic owner change when a widget is being removed from a holder if childrenPerOwner is not set to true.
Proposed wiki changes:
| childrenPerOwner | false        | If set to true, a new child will have its _owner_ set to the player that drags the child into the holder.  It will also remove the owner when the card is dragged out of the holder. <br />This is set to true when you add a new hand. |
> Prevent owner change when childrenPerOwner false

- client/js/widgets/widget.js
A typo causes a crash when writing debug log information.
> fixed crash when `ROTATE`ing a collection while JSON editor is active

- client/js/connection.js
- client/js/main.js
- client/room.html
Change #ghetto-link to #legacy-link in three places; changed the phrase "in an advanced" editor to "in the legacy editor".
Change link in room.html to legacy-editor.htm.
> Replace "ghetto" by "legacy" in UI

- client/css/jsonedit.css
- client/js/jsonedit.js
- client/js/main.js
- client/js/tracing.js
- client/room.html
The sidebars on the right of the JSON editor are pretty wide right now. When writing complicated routines that is useful but the rest of the time it is basically a giant waste of space that can make the room look tiny depending on your resolution.
This PR adds a new button to the top row of commands that toggles the width between two presets.
We might have to tweak the values a bit but I think a toggle between a narrow and a wide preset is good enough. Adding a way to set the size freely is also possible but a lot more work and then people will ask for saving their sizes etc.
This PR should work fine as is but please use it as a base for further discussion.
> added toggle for wide/narrow sidebar to JSON editor

- .github/workflows/production-environment.yml
- .github/workflows/testcafe.yml
Looks like the action `textbook/git-checkout-submodule-action@master` we use in the automated tests to checkout the submodule is no longer supported by the maintainer. But the official `actions/checkout@v2` seems to just have an option to checkout submodules.
> fixed GitHub workflows

- client/js/widgets/widget.js
This is a replacement for #879, which was closed. Suggestions/review comments from that PR have been implemented.
Needs:
1) Good code review
2) Thorough testing of new array functionality for source collections.
3) Is there a way to add [] to the list of possible values for the `"collection"` property (or, for SELECT or TURN, the `source` property? I don't see how it can be done.
Addresses #875. With this PR, functions that accept an input collection can now accept an array
```
"collection": ["id1", "id2", "id3"]
```
The result is that the function will operate on an anonymously-named collection that consists of all the id's that actually are the id's of widgets.
Replaces `isValidCollection` by a new routine, `getCollection`, that returns either the key of the collection passed in, or the …
> Implement anonymous collections.

- client/js/widgets/widget.js
When providing `operand1` but not a `relation`, `IF` would show `undefined` in the debug output. Now it shows the `relation` it acutally used.
`GET` always showed the variable name instead of its content as its result. Now it shows both.
> fixed `IF` and `GET` debug output

- client/js/jsonedit.js
When I removed `F4`, I actually removed its widget from the list instead of shifting the hotkeys.
> fixed missing widgets in JSON editor F-keys

- client/room.html
`alternate icon` is not a valid `rel` value for a `link` and caused Chrome to use the PNG favicon instead of the SVG version.
> Update fix for Chrome favicon to use the SVG version.

- client/js/widgets/canvas.js
Since canvas uses a raw mouse mode, it did not respect its `clickable` property. Now it does. Also added:
`artist`- default `null` - If set to a player name or array of player names only those players can draw on the canvas.
Please suggest better names than `artist`. @bjalder26 suggested `writable` but that feels like a boolean property to me.
Completely untested.
> add `clickable` support and `artist` to canvas

- client/js/mousehandling.js
The main problem was that `moveTarget` was not saved per touch but only once. So if the first touch found a `moveTarget`, the second touch would try to move unmovable stuff.
I also added a check for `mouseStatus[target.id]` in the move and up conditions because you can move the same widget with two fingers and lifting the first one destroys the context for the second one.
Tapping onto the screen with multiple fingers like a madman no longer seems to cause any crashes anymore.
> improved multitouch resilience

- client/js/widgets/widget.js
This is a bit more complicated because of float rounding issues. You do not want `0.100000001` to show on your labels. So this looks at how many decimal places your `LABEL` `value` has and then rounds the result to that many decimal places.
Please test and give feedback.
> add support for floats with `LABEL`

- server/room.mjs
When adding the feature that guests are removed from the list, I did not think about the fact that other clients might still be connected with the same name. Now there is a check.
I hope that this is the cause for the problems Roger, Raphael and I had in a pr-test room recently.
> only remove Guests from players if no player has the name

- client/js/statemanaged.js
Instead of `["x","y"]` you can now use `["!x","!y"]` to inherit everything EXCEPT `x` and `y`.
Completely untested. As in: I did not even check if the site still loads.
> added inverted properties to `inheritFrom`

- client/css/widgets/pile.css
- client/js/widgets/card.js
- client/js/widgets/pile.js
- client/js/widgets/widget.js
- package-lock.json
- server/pcioimport.mjs
This supersedes #852 after a discussion and collaboration with @RaphaelAlvez. It adds two properties (one to cards, one to piles):
`onPileCreation` - Whenever this card forms a new pile, all properties from `onPileCreation` will be copied to the pile. A pile will only form if both cards have the same value for `onPileCreation`.
`handleCSS` - The CSS is added to the handle of the pile allowing arbitrary customization.
This PR also introduces css variables for the handle CSS
Setting --phPosition and --phSize should be enough for 90% of the customizations needed.
--phPosition: -15px;
--phSize: 40px;
the follow CSS variables are created based on --phPosition and --phSize. For further customization you can set them directly
--phX: var(--phPosition);
--phY: var(--phPosition);
--phHeight: …
> pile customization

- server.mjs
The returned path was missing `/assets`.
> fixed asset upload

- client/js/widgets/pile.js
Apparently real-world games crash now because of empty piles. This introduces a sanity check.
> fix crash with empty piles

- client/css/overlays/states.css
Update to make long variant names appear below the play symbol.
From:
To:
> Long variant name display fix

- client/js/overlays/states.js
A comparison was looking for `class == "update"`. Now it checks if it is one of the classes
> fixed "Update variant using current room state"

- client/js/overlays/states.js
Addresses #1001.  Minor change in the structure of buttons was causing the variants to be added as separate games.
> Fix addVariant

- client/room.html
- server/minify.mjs
Changes `<script type="text/template">` to `<template type="text/template">` and makes the `CS`, `JS`, and `CONFIG` replaces look like comments in their elements.
This change stops the replaces from being reported as errors as well as allows proper code folding of templates in some editors including Nova on macOS and Visual Studio on Windows.
> Editor QoL improvements

- client/css/widgets/label.css
Contains fix for https://github.com/ArnoldSmith86/virtualtabletop/issues/20
Still ctrl+click selectable in JSON editor.
> Fix selectability issue for label textareas that are read-only

- client/js/jsonedit.js
Please test if this fixes the same stuff that #1031 fixes.
This would be a less hacky solution but if the other PR fixes more stuff, I have no problem merging it instead.
> JSON editor tree view no longer steals focus

- client/css/jsonedit.css
- client/js/jsonedit.js
Currently it can be hard to figure out if there was an error in a complicated routine call, as only the erroneous statement shows up red. This PR bubbles the error up, so that the expandable arrow on any node will be red if one of its descendants had an error.
> Make expander arrows in the JSON editor red if one of their descendants has a problem

- client/js/widgets/widget.js
Looks like I failed to add borderRadius to css properties, so updates are sometimes delayed.
> FIX: borderRadius missing from cssProperties

- client/css/widgets/classes.css
- client/js/editmode.js
- server/fileupdater.mjs
- tests/testcafe/tests.js
Re-sizable replacements for pin and pawn.
Pin scales only according to the width of the widget. Pin also has `--borderColor`, `--borderWidth` (3), `--pinWidth` (40), `--pinLength` (80 - values less that 50 do not extend beyond the pin head), & `--pinAngle` (-30) css variables allowing customization. Old pin available as 'legacyPinPiece' and border variables have been added to it.
Pawn stretches to fill widget (designed aspect ratio is 2:3). Old pawn available as 'legacyClasicPiece'
> new `.pinPiece` and `.classicPiece` css

- client/js/widgets/widget.js
When an invalid src is input for the AUDIO function it creates an audio element that will not be cleared from the DOM tree.  The reason why it will not be cleared is because currently unless a length is set in the JSON the JavaScript will remove the element once it has finished playing.  Since an invalid audio won't play, the element won't be cleared.
The point of this PR is to clear it immediately.  If there is an error with the AUDIO, then the audio element will be removed.
An invalid src should quickly be cleared from the developer tools.  A valid one should be cleared after the set period (default, when the audio ends).
To see it "work", just open these two rooms.  Open the developer tools to the elements tab, and start clicking the button.
PR: http://212.47.248.129:4039/pr-test …
> Clear erroneous audio element when invalid audio

- client/js/widgets/widget.js
The fix was already in the code but the variable just was not used.
> fix debug representation of `return`ed collection for `CALL`

- client/css/jsonedit.css
- client/js/jsonedit.js
Fixes #1066. Also fixes a problem where the arrow of the node with a problem was not painted red.
The pr-test room contains a small test taken from the pr-test room of #1040. I'm pretty sure that @bjalder26 had a better test room for that PR, but I don't know where it is now.
http://212.47.248.129:4068/uz1y contains @ArnoldSmith86's original example - sit in a seat and press New Game.
As I had to make a pretty global change to the css, I'd appreciate some real testing. It should be pretty benign, but still.
> Fix red color on children of offending node

- client/js/serverstate.js
Invalid widgets will not be added. Examples are widgets without `id`, with non-existant `parent` or cards without `deck` or `cardType`. They will produce error messages in the browser console (except for non-existant `parent`, I think).
When adding the widget failed, it is removed "properly" by calling `removeWidget`. _But_ if that _also_ fails, it currently crashes the client. An example are cards with their `deck` set to an existing widget that is not a deck.
> fixed crash with invalid widgets

- client/js/jsonedit.js
This PR does not change the fixed order at the top of the JSON (type, id, ...). All other properties were just shown in alphabetic order. With this PR this bottom block will be split into three parts: all other known widget properties (the yellow ones), then a block with all custom properties (the orange ones) and then another block with all the routine properties.
> group custom and routine properties in JSON editor

- .gitpod.yml
- tests/testcafe/gitpod-vnc/install.sh
- tests/testcafe/gitpod-vnc/novnc-index.html
- tests/testcafe/gitpod-vnc/start-vnc-session.sh
- tests/testcafe/gitpod.sh
- tests/testcafe/tests.js
Allows arguments to be passed to testcafe-gitpod similar to other testcafe scripts.
Also adds files for setting up a VNC environment needed to run testcafe in graphical mode with gitpod. This can be set up using this branch then another branch can be checked out for testing (the script installs the tools needed outside the container's /workspace directory - changes do not persist when the container is stopped, but they are also not removed when switching branches).
To run graphical tests in gitpod using VNC, simply use `source tests/testcafe/gitpod-vnc/install.sh` to install and start VNC (also installs firefox). Open a browser to the suggested port 6080 to see the graphical desktop. Then use `npm run testcafe-firefox` to run tests.
> Improve testcafe-gitpod

- client/js/domhelpers.js
- client/js/jsonedit.js
Fixes #1123 
Default value for an INPUT select field can be set in two ways. Setting the field value to the value of one of the options, or setting `selected: true` within the option to select.
> Default values in INPUT select field

- server.mjs
When generating a new room (by going to virtualtabletop.io directly), this PR should prevent the rare case where the generated room ID already exists. It just regenerates random room IDs until it finds an empty one.
> prevent redirecting to an existing room

- server/fileloader.mjs
- server/pcioimport.mjs
- server/room.mjs
I added those options when I introduced the `config.json` file but I never actually made them work. I am pretty sure that they do now, though.
> make `directories.save` and `directories.assets` in `config.json` work

- client/js/widgets/pile.js
- client/js/widgets/widget.js
- tests/testcafe/tests.js
Fixes #1111: shuffle no longer creates ambiguous z values. Instead of a random z assigned to each shuffled widget, the widgets are put in a random order, then each is brought to the front of their layer in turn. Shuffled widgets will now be in front of any widgets that were not shuffled (previously widgets on the same layer could remain in front of [some] of the shuffled widgets).
> result of shuffle is no longer ambiguous

- client/js/main.js
- server.mjs
- server/fileloader.mjs
When uploading assets directly, the limit was 100MiB but when reading from a vtt file, the limit was 2MiB (and anything bigger was just silently ignored).
Now the limit for both is 10MiB and if an asset in an uploaded game is bigger, it gets rejected with an appropriate error message.
> increase asset limit from 2 MiB to 10 MiB

- client/js/widgets/widget.js
Fixes #1070 
This could result in games breaking if they rely on all falsy results of CALLed routines being converted to `null`.
> CALL can return falsy value

- client/js/widgets/holder.js
- client/js/widgets/widget.js
Fixes #1116 
This could change the behavior of some games that make use of owner arrays. Currently a player in an owner array can move a card into the hand to become the sole owner of the card, but this PR changes that behavior. All players in the owner array would continue to see the card.
> Move to seat sets `owner` before moving to `hand`

- client/js/widgets/holder.js
- client/js/widgets/widget.js
Reverts ArnoldSmith86/virtualtabletop#1139
I think this PR breaks MOVE to seat (and then from seat to hand) behavior.  But only sometimes.  Not sure exactly why or how or when, but now when you MOVE to a seat, sometimes the player pressing the button gets all of the cards.  I noticed this in Hearts, which I'm still tweaking.  So I tested it in Spades which was definitely working and in the 3rd variant (seats) of the Hands tutorial.  Intermittently but not every time, sitting in a seat and MOVEing to that seat gives that player all the cards.
> Revert "Move to seat sets `owner` before moving to `hand`"

- client/js/domhelpers.js
The last minute change to `mapAssetURLs` caused it to no longer remove the initial slash if it just receives an asset string (as opposed to CSS).
> fix audio with `urlPrefix`

- client/js/jsonedit.js
I just rediscovered these tree view improvements in #850. I do not think that #850 will be prioritized anytime soon but these changes are unrelated and probably helpful.
It shows the `cardType` of cards, `text` of buttons and `classes` of basic widgets in red.
> tree view shows identifying properties

- client/js/overlays/states.js
PR #1087 missed this one.
On my local test server I see a reconnect/reload after downloading a state now. I do not see that on the production server. I want to see if it also happens on the PR test server. I probably want to fix that.
> fix state downloads when using urlPrefix

- client/js/widgets/widget.js
PR #1087 did not map asset URLs in widget stylesheets. This PR fixes that.
So this:
```JSON
{
"id": "background",
"css": {
"default": {
"background-image": "url(/assets/-607361757_73020)"
}
}
}
```
works with this PR (https://test.virtualtabletop.io/PR-1142/pr-test) but does not without it (https://test.virtualtabletop.io/PR-1141/owpw).
It does however work in production and on the beta servers because they do serve the asset under `/assets/-607361757_73020`.
> fix widget stylesheets when using `urlPrefix`

- .github/workflows/testcafe-chrome.yml
- .github/workflows/testcafe-firefox.yml
This PR splits Firefox and Chrome TestCafé tests in separate workflows. That should hopefully make it run in parallel.
> parallelize testcafe tests on GitHub

- client/js/mousehandling.js
This problem is similar to #1144 but has a different origin.
The hand holder is usually at the bottom of the room. Phones nowadays trigger system gestures when swiping from the bottom. When dragging a card from the hand, you could trigger the system gesture to switch apps or go to the home screen and the card being dragged would just stop in mid air causing the same issues as described in #1072 (the parent is set to null but the owner is not).
This PR listens for the `touchcancel` event which is triggered in situations like this and handles it like it handles a normal `touchend` event. So it will pretend that the player let go of the card in that place.
> listen for touchcancel

- client/js/widgets/widget.js
PR #903 changed the way drop targets work but did not update the `owner` behavior of cards. As a result it caused #1072. See that issue for the problem description. This PR should fix the situation by triggering the holder leave behavior as soon as the drop target for the dragged card changes.
> fix that moving a card half out the hand does not update owner

- client/js/widgets/widget.js
Incrementing a label by `null` obviously does not make a lot of sense but it should not crash the client. This PR converts it to a number before detecting the number of decimal places (which was where the crash happened).
> fix incrementing label by `null`

- client/js/statemanaged.js
If a property gets set to `null`, it reverts to its default value. For custom properties the function `getDefaultValue` returned `undefined` instead of `null`. No other part of the VTT code expects `undefined` in the delta though so it gets treated as "property was not changed at all".
I am pretty surprised that this did not come up earlier and I am a bit afraid that this might break subtle things in a game or two.
I am also pretty sure that this should be changed though.
> the default for custom properties should be `null` instead of `undefined`

- client/css/layout.css
- client/js/main.js
- client/room.html
I had this idea yesterday that this might look nice on phones with AMOLED screens when using fullscreen.
This PR adds a new toolbar button after the sound button that toggles between the normal background and toolbar and black versions with dimmed images.
Please make suggestions about where to put this. The players overlay is already called "Players & Settings" - maybe this is the point where we move sound and lights there?
> lights off

- client/js/widgets/widget.js
- server/pcioimport.mjs
It was already checking for a valid widget ID but `isValidID` requires a second parameter now. Probably a merge error at the time this was added.
> fix crash when `CALL`ing invalid widget

- client/js/widgets/widget.js
Provides basic support for widget stylesheets to css `@`rules. Intended use is `@font-face` and `@keyframes`. Multiple `@font-face` rules can be added to a widget if they differ in trailing whitespace. Should work with other `@`rules that typically take blocks (though I can't think of any that would be useful currently - `@property` might be nice when supported in Firefox and Safari).
Support for nested css blocks added.
> css @rule selectors

- server/room.mjs
I've never really been thrilled with the default player colors. This PR changes the default colors selected for new players (somewhat reducing the value component of the color).
The value is reduced the most for the primary colors (pure red, green, blue: value reduced from 255/255 to 140/255) and the least for the secondary colors (yellow, cyan, magenta: value reduced from 255/255 to 220/255). This [CodePen demo](https://codepen.io/robartsd/pen/LYOEZrX?editors=1100) shows the existing spectrum of colors chosen, an approximation of the new spectrum chosen (gradient points at 15 degree hue angles are accurate, but colors between those points may be slightly different), and sample spectrums of colors that are desaturated enough to be ignored when choosing the hue for a new player color (this …
> modify default player colors

- client/js/widgets/canvas.js
- client/js/widgets/widget.js
Fixes #1207 
If a canvas is enlarged, the enlarged widget updates with the canvas. A child canvas is also copied, but like other child widgets, it is not updated live in the enlarged widget.
> copy canvas image to enlarged

- server/config.mjs
When #1087 added the new config parameter `urlPrefix`, everyone had to add it to their `config.json` or the server would immediately crash.
This PR now adds a fallback so that config parameters that are not defined in `config.json` will be read from `config.template.json` instead. This means you now only have to set stuff in `config.json` if it is not the default.
> missing settings are read from `config.template.json`

- client/js/serverstate.js
- client/js/widgets/basicwidget.js
- client/js/widgets/button.js
- client/js/widgets/timer.js
- client/js/widgets/widget.js
It is not easy to make `svgReplaces` evaluate to `null` but it is possible with `inheritFrom`. This causes a crash which this PR fixes.
Similar behavior happens for `faces` where the code assumed it is an array. The resulting crash should now also be fixed.
Additionally this PR fixes a crash when indexing a variable that evaluates to `null` in a dynamic expression.
> fix crashes with invalid values for `svgReplaces` and `faces`

- client/js/jsonedit.js
`inheritFrom` changes what `getDefaultValue` returns because reasons. This breaks the "is custom property" detection of the JSON editor so this PR calls `getDefaultValue` on a clean widget instead.
> fixed ordering of custom properties with `inheritFrom`

- server/room.mjs
Not sure how this slipped through but the room tried to write something into the trace file before initializing it.
> fixed server crash when tracing is enabled

- client/js/jsonedit.js
Sort widgets under mouse so that widget on top gets F1 and function keys are assigned in descending order. Fixes #401
> Assign function keys using descending Z-order.

- client/js/widgets/label.js
If a label receives a delta with `twoRowBottomAlign` but without `text`, it will show `undefined` afterwards.
> fixed undefined label text

- client/js/editmode.js
- client/js/jsonedit.js
This should fix #1280. See https://github.com/ArnoldSmith86/virtualtabletop/issues/1280#issuecomment-1196392512 for a description of what caused the problem.
> fixed slow JSON editor when editing widgets with many children

- tests/testcafe/tests.js
This is essentially a redo of #1100.  I put that one on hold because it was so large and also introduced new things.  This PR just updates existing games.  Most changes are minor or cometic.  A few games got big makeovers.
•	Agra. Fixed minor layering issue and attribution link. Added shuffle on recall to 3/4/5 exchange tokens.
•	Alleys. Added seats. Changed pawns so they inherit seat color. Updated restart button code.
•	Chinese Checkers. Added seats. Combined all variants into one using an option button to pick style of marble.
•	Connex.  Added seats and next turn button
•	Dix Dice. Added seats and restart button.
•	Dominoes. Changed rotation method. Changed cards to SVGs. Add 15 pip dominoes and colors. Added seats. Expanded number of players. Added options for scoring …
> Fixes and enhancements to 15 games

- client/js/jsonedit.js
Hopefully fixes #643.
Simple change to the R.E., but I'm not sure what else in colorization might be affected.
> Change R.E. for non-string non-numeric expressions to exclude `$`

- client/js/jsonedit.js
- client/js/widgets/spinner.js
This is intended to fix #763.
Except for the `faces` property of `basicwidget` and the `dropTarget` property of `holder`, I believe that the caret is placed properly. Basically this involves changes to `jeInsert` to figure out what is being done, and changes to `jeSetAndSelect` to get the selection boundaries correct.
- The code seems somewhat special-cased to me, but this is a pretty fiddly thing to get right. I'd appreciate a code review.
- For the two remaining cases, the issue is that the offsets of where to put the selection are computed using an incompletely formatted version of the JSON (specifically, it uses `{ "type": "card"}` instead of the version including newlines and leading spaces produced by `stringify`. I don't see a simple way to solve this problem; perhaps someone else …
> Caret is now placed properly in most cases

- client/js/editmode.js
The y-coordinates are computed by centering them around the pins. This PR just rounds the result to avoid random decimals. Fixes #1307
> Round y coordinates of checkers and classic pieces.

- client/js/editmode.js
- client/js/jsonedit.js
This adds a new text box below the "use inheritFrom checkbox" to allow the user to enter a set of properties to be inherited. Leaving it blank will result in all properties being inherited (as before).
> Allow inheriting of a subset of properties.

- server.mjs
Loading `https://virtualtabletop.io/assets/833604844_1066812,` would not finish the request until some kind of timeout. Now it should return 404.
> return 404 for invalid asset names

- client/js/jsonedit.js
I fell for this so often.
We check `typeof variable != 'object'` and forget that `null` is also type `object`.
> added a check to several JSON editor commands to prevent crashes for css===null

- client/js/jsonedit.js
Fixes #1351.
`jeDisplayTree` wass being called by `removeWidgetLocal` for each widget in the selection. This PR wraps the  for loop in `je_removeWidget` with `batchStart` and `batchEnd`.
> Fix multiple calls to tree display in multi-widget deletion.

- client/css/overlays/players.css
- client/js/overlays/players.js
In case a particular game wants to make it easier for players to point to things they may want to increase the cursor active duration so that the cursor stays visible longer before fading away.
The https://test.virtualtabletop.io/PR-1358/pr-test has a test of setting the active duration to 2000 (milliseconds). Note we could parse units to make it accept the same as an animation time (e.g. 2s or 2000ms) but I don't know if this complexity is necessary.
> Allow customizing a cursor's active duration.

- client/js/widgets/widget.js
This fixes #1359 and also paves the way for parents to apply changes based on child z ordering which can be used to optimize large piles.
> Add applyChildZ function which applies inheritChildZ

- client/js/widgets/widget.js
Fixes #1398. There was a check already that was supposed to prevent the crash but back then I forgot that `typeof null == "object"`.
> fixed client crash when indexing a variable containing null

- client/js/jsonedit.js
Fixes #1376. The grid commands assume that the `grid` property is a top-level widget property but their contexts match a `grid` property even if it is nested inside another property.
This PR changes the context so that the commands are only displayed on the top-level `grid`. A proper fix would make them work everywhere instead.
> fixed JSON editor client crash when setting grids inside cardDefaults

- client/js/jsonedit.js
- client/js/widgets/widget.js
Fixes #1431.
This adds `range` in addition to the existing `in` and `collection` parameters to `FOREACH`. `in` takes precedence over `range`, which takes precedence over `collection` if more than one is specified.
The value to `range` is a range of the form `[start, end, step]`. If `step` is omitted, it is assumed to be 1 if `start` < `end` and -1 if `start` > `end`. The `loopRoutine` is called once for each element of the resulting range, passing the range element as `value`.
> Add 'range' option to FOREACH

- client/js/geometry.js
- client/js/widgets/widget.js
This supports arbitrarily complex transformations including perspective and also leans on the browser to do the conversion between coordinate spaces. Fixes #1420.
> Use DOMMatrix transforms to convert points between spaces.

- client/js/jsonedit.js
Fixes #1461.  I probably would have put minX and minY first and then max, but it doesn't matter since the editor seems to automatically alphabetize them.
> Add maxX and maxY to JSON Editor Grid Options

- client/js/overlays/states.js
- server/room.mjs
If a room had the same public library game 60x before #1223, the migration would remove the duplicates but it would count each one towards the stars.
Also: a public library game is hidden if all its variants get linked to from other games in the room. This PR changes it so it is only hidden if it is not also starred.
> fixed state migration for duplicate games

- library/games/Medieval VNO/0.json
- library/games/Medieval VNO/1.json
- library/games/Medieval VNO/2.json
It used `"dropTarget": { "not": "allowed" }` which prevented several routine operations to operate on the children.
> fixed Medieval VNO direction indicator and NEXT button

- client/js/main.js
Adding `#tutorials` after the URL will pre-select Tutorials in the game shelf filters.
> support `#tutorials` to jump directly to Tutorials

- tests/testcafe/test-util.js
Issue #1553 documents why the compute check for `toLocaleLowerCase` currently fails for Chrome 109. This PR makes TestCafé accept the changed hash although I hope that this is temporary and will be fixed in Chrome.
> fixed TestCafé

- server/fileloader.mjs
The link in https://virtualtabletop.io/Citadels was broken because it referenced a different state ID in the VTT file. This PR should fix that the content of a shared game would return the wrong state ID and on top it makes it load a different state ID from a link if there is only one in the file (which is the normal case unless it is a VTTC file).
> fixed loading old share links

- server/room.mjs
I missed this when I turned variant IDs into numbers. The target server tried to load variant ID `"serverMove"` instead of `0`.
> fixed moving a room to a beta server

- client/js/overlays/states.js
- server/room.mjs
If you transfer a vtts savegame to a different room, its reference to the game it is based on no longer works (because the new room does not have the same game with the same ID). This PR fixes multiple issues that were uncovered by this behavior:
- There are client crashes if certain game metadata does not exist or is not a string (mainly `name` and `mode`).
- If a state has an undefined image, the client would request `/undefined` which triggers loading room `undefined`. Incidentally that room was broken on my local machine which crashed the entire server.
- Saving the game _again_ would try to load the metadata for the new savegame from the game it was based on. That link is invalid so it produced a completely broken state. Now it falls back to the old savegame which also has all the …
> fixed re-saving a savegame if the source game is no longer there

- client/css/layout.css
My wife's phone uses Android 9 and its WebView 85.0.4183.101 somehow displays the logo in the wide toolbar really tall (the `img` but not the image), making lower buttons inaccessible.
This PR simply sets a fixed height on the `img`.
> fixed wrong logo height on oldish Android

- client/js/geometry.js
- client/js/widgets/widget.js
When cards are transformed they are effectively positioned relative to their transform origin. Fixes #1582.
> Use the offset from the transform origin to calculate move delta.

- client/js/widgets/widget.js
Note this is using a bit of a hack, the delta.id is in fact defined if the widget id changes as well. I'm not sure if we have a signal for the widget having just been created yet but the id trick works unless some programmatic code also changes the id while reparenting. This fixes #1590.
> Only transition widgets which weren't just created.

- server/room.mjs
If a room is broken and does not contain a list of states or stars, it should not crash the server.
> fixed crash when unloading rooms

- .gitpod.yml
This switches Gitpod workspaces created from this repository to use the gitpod/workspace-full-vnc image instead of the default gitpod/workspace-full image. Starting up a Gitpod workspace takes about the same time, but the image comes with a visual desktop served to noVNC on port 6080 and Chrome built in. This means that testcafe can run visually (or headless) in Chrome in the workspace with no additional setup.
> Use gitpod/workspace-full-vnc

- client/js/widgets/widget.js
It is very easy to accidentally remove the parent of a widget when in edit mode. This makes all widgets that have movable set to false behave as if fixedParent is set to true when being moved in edit mode.
> Behave as if fixedParent is true if only movable in edit

- client/css/layout.css
- client/js/domhelpers.js
- client/js/jsonedit.js
- client/js/widgets/widget.js
Added a simplified 'palette' input type that takes a list of colors as options. 
```
{
"type": "palette",
"label": "Color",
"options": [
"#897349",
"#89dd98",
"#fff",
"#dbdc00"
],
"variable": "playerColor",
"value": "${playerColor}"
}
```
It uses --VTTblue as the selected outline and checkmark color.
----------------
Proposed wiki update:
* `type`: 
......
* `palette`_displays colored radio buttons_-stores the selected value. Unlike the `color` field, this offers a consistent viewing experience across browsers and forces the players to choose from a palette of options.
* `colors`: _array_ - displays the color choices available to the player. Accepts most color formats (html-friendly, hex, rgb, rgba, hsl, hsla).
> 'palette' input type

- server/room.mjs
This fixes #1635. When updating the currently loaded save game, the button deleted `_meta` from the saved file which also removes version information. This PR fixes that.
To mitigate broken states now saved on the server, this PR also looks at all save games the next time when a room is loaded. If it finds states without version information, it looks at the date when the state was saved, compares it to the most recent version changes and sets the version in the file accordingly, fixing it for the future.
If a file was broken, loaded before a version bump and then resaved afterwards, it might still be broken, because it might have skipped one or more file updaters.
Also: this assumes that the server updated to new commits as soon as they went live. This should be true for the production …
> fixed save states without version

- server/room.mjs
When adding a game to the public library using the GUI, the server would crash if it could not find an asset used by the game.
This PR fixes two situations where this might happen:
1. If the asset actually does not exist. In this case it now shows a popup to the user before screwing things up.
2. If the asset is used in another public library game and does not exist in the global assets directory. In this case the asset is now copied from the other game.
> improved asset handling when adding games to the public library

- client/js/widgets/widget.js
While working on the undo feature in #1627, I noticed that moving a widget on a `grid` caused extra deltas to be sent. The cause was this missing `await`.
> added missing `await` in `snapToGrid`

- client/js/overlays/states.js
Uploading states are now always displayed no matter what filters are applied in the library.
This was the easiest way to fix a crash where uploading states were missing metadata for the filtering.
> always show uploading games

- library/games/Liar's Dice/0.json
The game used `type: dice` as a custom type but now that it is an actual type, it no longer works as expected. This PR intends to fix that.
> fixed dice in `Liar's Dice`

- client/js/overlays/states.js
If the game library images are not in the cache and you connect through a slow connection, it would load _all_ the library images first before loading any assets of the active game.
This PR adds lazy-loading so that game images are only loaded when actually visible on the screen.
Note that browser dev tools can emulate slower connections and disable cache (top right corner for Firefox):
> lazy-load game library images so the active game loads first

- client/js/widgets/scoreboard.js
When you click a scoreboard currently, the overlay values default to the player in the first seat and the first round.  This PR changes that so that the default value is the playerName.
I want to change the default round to be the next round.  But I wanted to go ahead and get this started because I had so much trouble doing it.  Hopefully the round will be easier.
> Clicking scoreboard shows better defaults in options

- library/games/Egyptian Epochs/0.json
Small tweaks to improve Egyptian Epochs (similar to Ra) in the public library:
- Resized text labels to avoid text being cut off;
- Removed unneeded z values from many widgets;
- Used inheritance where possible to reduce the size of the json file and make future edits easier;
- Added an "are you sure?" prompt to the Setup button and also added some missing items to completely resetting the game (recalling all decks and ensuring player scores are reset)
> Public Library: Small fixes for Egyptian Epochs

- client/js/widgets/label.js
Added ability to specify `tabindex` on labels to control navigation between labels when they are editable. Set this with:
`"tabIndex": 𝑥`.
Similarly:
`"placeholderText": "𝑦"`
Thanks to LawDawg for explaining how things get added to the JSON editor.
> Added ability to specify tabindex and placeholder text for labels

- client/js/widgets/canvas.js
With this PR, you can use `transparent` in the canvas `colorMap` property to let the widget underneath the canvas shine through.
> support transparent canvas

- client/js/widgets/widget.js
`TIMER` with `mode: set`, `mode: dec` and `mode: inc` was not working with collections since #881 because the variable `collection` would not be filled in that code path.
I noticed this because it broke the timer in `The Team II`.
> fixed TIMER when using a collection

- client/js/widgets/scoreboard.js
When changing the property `verticalHeader`, the scoreboard gets not updated immediately. This fixes that.
> fixed updating scoreboard for verticalHeader

- library/games/Animal Race/0.json
It mainly crossed my radar because it was using an external link. Turns out it was a duplication error in the first place.
> remove unused deck from Animal Race

- client/js/jsonedit.js
- client/js/overlays/states.js
- server/minify.mjs
After merging #1482, the production server did not start. The cause is that the minified Javascript contains `$&` and that it is put into the HTML by replacing `//*** JS ***//` by the minified contents. The `String.replace` function treats `$` as a special character to access a few parts of the matched results so the `$&` was replaced by `//*** JS ***//` again which made the resulting Javascript invalid.
Turns out this is the same problem that made me insert a bunch of `String.fromCharCode(36) // the minifier does not like $ or \x24 here` into the code.\n\nThe fix is to use an anonymous function as the replacement in `replace`. Its output is used as is.
> fixed minification

- client/js/widgets/widget.js
This fixes #1690.
This looks like a safe fix. As things currently stand, `a.faceCycle` will be `undefined` unless it was specified in the `FLIP` call. After this fix, `a.faceCycle` will be `null` if not specified in `FLIP`, and the flip routines in basicwidget and card treat `undefined` and `null` identically.
> Fixed typo in name of faceCycle property in FLIP

- config.template.json
- server.mjs
The `config.json` now has a new setting `adminURL`. If you set it to `/admin`, your VTT server will output administration information using that URL.
Currently it shows all active rooms with the loaded game and active players as well as the latest `deltaID` to get an idea about the room activity:
> added admin overview page

- client/js/editor/layout.js
- client/js/editor/sidebar/toolbox.js
- server/minify.mjs
This is a new version of #694. Later this should be part of the widget library which should replace the Add Widget overlay. But for now this is a simple version that we can use in the meantime.
> added widget buffer to copy widgets between games

- client/css/overlays/players.css
- client/js/editmode.js
- client/js/mousehandling.js
- client/js/overlays/players.js
- client/js/widgets/widget.js
- server/fileupdater.mjs
- tests/testcafe/editor.js
- tests/testcafe/publiclibrary.js
This is keeping it simple. It might be a good idea to highlight the widget instead of showing a cursor but this PR really just hides the cursor.
It is added to new hands by default and also to any holder with `childrenPerOwner: true` by using a file updater.
> added property `hidePlayerCursors`

- client/js/editor/sidebar/properties.js
In production it only works the first time and also breaks stuff because it removes the visualized deck from `widgets`. This should fix that.
> fixed dropTarget setting in editor

- client/js/jsonedit.js
- client/js/widgets/widget.js
A new parameter for `MOVE` that makes it possible to fill cards to target holders/hands up to a defined value.
I am not sure how this should work with `count` and `fillTo`. The way I did it now, `fillTo` defaults to `null` and if it is set, it basically overrides `count`. A different way to do it would be to make `fillTo` boolean and use `count` for the count but then you would have to set two parameters every time you want to use `fillTo`.
> added `fillTo` to `MOVE`

- client/css/widgets/card.css
This reverts a small part of #1654 that was not really necessary but broke an example in the Enlarge: Cards tutorial.
> fixed cut off enlarged view

- client/js/statemanaged.js
`inheritFrom` can have these forms:
```JSON
{
"inheritFrom": "seat"
}
```
```JSON
{
"inheritFrom": {
"seat": "*"
}
}
```
```JSON
{
"inheritFrom": {
"seat": [ "width", "height" ]
}
}
```
```JSON
{
"inheritFrom": {
"seat": [ "!width", "!height" ]
}
}
```
This PR adds these forms because I stumbled over them multiple times wondering why they weren't working:
```JSON
{
"inheritFrom": {
"seat": "width"
}
}
```
```JSON
{
"inheritFrom": {
"seat": "!width"
}
}
```
> allow strings in `inheritFrom`

- client/js/main.js
It was checking for the Add Widget overlay which is no longer accessible without edit mode.
> fixed crash when pressing ESC on an INPUT overlay

- server/connection.mjs
Handle websocket errors by disconnecting the client. Hopefully prevents server crashes.
> handle websocket errors

- client/js/editor/sidebar/assets.js
- server.mjs
If downloading an asset URL failed on the server, the entire server would crash. This improves the URL detection a bit and catches errors if the download failed.
> prevent crashes in asset downloader

- client/js/widgets/card.js
Previously the default was to not set a color at all which made it inherit the color of its parent. Which leads to transparent text in holders or something.
> card text layers default to black color

- client/js/editor/toolbar/undo.js
When pressing the Undo button in the editor toolbar, you can undo the intial room state loading which completely removes everything from the room.
I want to improve more things about Undo and auto saving but I feel like we should fix this pretty quickly because it is very destructive.
> prevent undoing initial state load

- client/js/widgets/card.js
Fixes a problem created by #1874.
If a text layer use something like ` "css": "color:darkgray",` but did not just directly specify `'color": "darkgray"` as was the case in Shattered Dominions, the card text was being set to black and the css was being ignored.  This PR adds a check to see if a css color has already been set and then will not apply the default black.
> Fix problem from setting card text layers to black by default

- .github/workflows/production-environment.yml
The GitHub test Production Environment fails more and more often because the started server is not ready yet. This PR makes the test wait 5 more seconds before attempting to reach the server.
> increased production test wait time

- client/js/widgets/widget.js
When rendering a copy of a widget, I deleted properties like `x` and `y` to make sure it is displayed where I want it to.
Unfortunately I did not think about `inheritFrom` so in some cases deleting `x` simply leads to inheriting it from somewhere else.
This PR explicitly sets these values to their defaults so they do not get inherited.
> fixed `INPUT.choose` visualization inheriting undesired properties

- library/games/Cirque de la Cascade/0.json
- library/games/Floodplain Frenzy/0.json
Update public library games _Floodplain Frenzy_ and _Cirque de la Cascade_, changing the `.droptarget` class so that hovering with a droppable token shades the hex rather than showing the square outline of the holder.
> Public Library: Add hex highlight effect to 2 games

- server/pcioimport.mjs
Apparently nobody tested older PCIO files with #1915.
> fixed PCIO import

- client/js/widgets/widget.js
Pressing a button in an `INPUT` overlay quite often triggers routines that take a while. This PR hides the Cancel button and changes the OK button to Working so the player knows that they hit the button. It also disables the buttons - not sure if that is necessary.
I will probably add something similar to clicks in the room but that needs more thought and can be its own PR.
> feedback when pressing `INPUT` button

- client/js/domhelpers.js
If you used the icon picker in the JSON editor, it gets filtered to either fonts or images. In production that filter is not reset when using it in the metadata again. This PR fixes that.
I also noticed that leaving the icon picker open in the metadata and then switching to edit mode leads to problems. So this also closes the icon picker in the Game Shelf whenever you use it somewhere else.
> always show all symbols for metadata icon picker

- client/js/overlays/states.js
This resolves #1938 by only allowing files to be dropped if the Game Shelf is visible.
> only allow dropping files in Game Shelf

- client/js/editor/sidebar/properties.js
It tried to use the first cardType for rendering the face previews. Now it shows a message if no cardTypes are defined.
> fixed deck editor crash when the deck has no cards

- client/js/editor/toolbar/save.js
Especially if you create an in-progress save game, remove the origin game and then enter edit mode, it would crash because the Save button would try to read from the deleted game.
> fixed crash when editing an in-progress game save

- library/games/Carnival/0.json
There was a problem in the last round with sorting.  This fixes that.
It also fixes the problem that if the player changed their mind after staging a card to play, the previously selected cards would also move to the player's hand.
> PL Update Carnival to Fix Sort Problem

- library/games/Word Whirl/0.json
When the player board is rotated to the left a bunch, it has a negative angle big enough to result in a negative angle when comparing to the correct angle. And modulo is not enough to map to 0...360. This now adds a simple check that fixes negative angles.
> World Whirl: fixed correct rotation detection

- client/js/editor/sidebar/assets.js
Fixes #2033 which was caused by an audio file among the assets. The compression table now simply shows Error for any asset it could not compress.
> fixed asset compression when encountering sound files

- client/room.html
Fixes #2034 by removing the HTML that should not be used in the first place.
It was triggered because the variant metadata ended up in the game metadata which is not always the case (and should probably be fixed).
> removed broken language from game link

- client/js/editor/sidebar/properties.js
Fixes #2030 by setting `step=any` on those inputs.
> allow any number in generic editor inputs

- client/js/overlays/states.js
Fixes #1998. Library images are lazy loaded (so only when scrolled into view) to prevent loading all the library images before loading the game that is actually loaded.
This PR keeps track of which images were loaded already so that the next metadata update from the server does not set every image to lazy load again.
> fixed image flicker in game shelf

- client/js/jsonedit.js
The command `Add basic widget` in the JSON editor currently adds `type: basic` to the added widget implying that that is required. In fact any value for `type`, that is _not_ one of the other widget types, results in a basic widget.
> removed type when adding basic widget

- client/css/widgets/scoreboard.css
I could not figure out how to make it sticky at the bottom while scrolling so on Safari, you will have to scroll down to the totals row for now.
> fixed scoreboard totals row position on Safari

- server/pcioimport.mjs
This fixes importing holders with an upward spread direction but it still only works for default card dimensions. I will probably continue working on this soonish but we might as well merge this obvious typo.
> fixed typo in PCIO importer

- client/js/widgets/scoreboard.js
- library/tutorials/Scoreboard/0.json
- library/tutorials/Scoreboard/1.json
- library/tutorials/Scoreboard/2.json
The CSS variables `--firstColWidth` and `--columns` were not set reliably and disappeared whenever the CSS was updated without redrawing the entire scoreboard table.
This PR also introduces property `firstColWidth` so that the `50px` can be changed.
> fixed inconsistencies in scoreboard CSS

- client/js/widgets/basicwidget.js
Now the children should stay in place and adding/removing `html` or `text` properties should update the widget as expected.
> fixed that basic widgets would lose their children when editing their `html`

- library/games/Cirque de la Cascade/0.json
Corrects a mistyped property in public library game Cirque de la Cascade, when playing on the advanced/alternate board side. This allows player pieces to snap to hex O18, consistent with other hexes on both sides of the board.
> PL Cirque de la Cascade: Correct mistyped property on alternative board

- library/games/Egyptian Epochs/0.json
- library/games/Egyptian Epochs/1.json
In simplifying Egyptian Epochs routines to use `skipTurn` to skip players without any suns, an error was introduced meaning that `skipTurn` was also set on players that won an auction. This corrects this by ensuring that current-bid holders inherit from the future sun holder instead of the active sun holder.
> PL Egyptian Epochs: Fix bug with skipTurn introduction

- client/js/widgets/widget.js
A call to `jeLoggingRoutineOperationSummary` did not check for `jeRoutineLogging` first, making it crash when not in edit mode.
See https://discord.com/channels/871236474589286461/979427827587903580/1256688714130653214 in Online Card Players Discord.
> fixed client crash in `TURN`

- client/js/editor/sidebar/toolbox.js
Putting widgets from the widget buffer into the game now checks if their parents exist in the buffer or in the game. If a parent does not exist, it will be set to `null` instead.
Additionally this gives an error message if a referenced deck does not exist.
> fixed widget buffer with invalid parent

- client/js/editor/sidebar/assets.js
The button text `Upload Assets in Same Format` can very easily interpreted as a requirement to zip the assets again before uploading but that does not work. This text should lead to less confusion.
> clarify mass asset upload in editor

- client/css/jsonedit.css
- client/js/jsonedit.js
A button next to the filter input that collapses all nodes in the tree. Fixes #2170.
> added a Collapse button to the editor tree

- client/js/editor/sidebar/json.js
- client/js/jsonedit.js
Fixes #2207. It was regenerating the output for every selected widget instead of doing it once when all of them are selected.
It still does way too much work when selecting widgets but for now this should be fast enough.
> improved performance when selecting multiple widgets

- client/js/widgets/widget.js
The case was already handled in the code but the error message referenced the wrong variable.
> fixed crash while CLONEing when the given id already exists

- client/js/widgets/widget.js
Fixes #2189. By absolute chance I did `${PROPERTY x OF $var}` and `$var` evaluated to `[]`. And `isValidID` returns `true` for an empty array because it works with arrays for other reasons.
> fixed crash with PROPERTY x OF array

- client/css/layout.css
- client/js/domhelpers.js
- client/js/jsonedit.js
- client/js/widgets/widget.js
Fixes #2188. I hope this is a good solution. Children will now be visible on UI representations of a widget (like in `INPUT.choose` or the `dropTarget` buttons in the properties panel) _unless_ they are in a holder and match its `dropTarget`. So a card dropped into a holder is not rendered because it is considered a different widget in that context.
> added option `visibleChildWidgets` to `INPUT.choose`

- client/js/editor/sidebar/json.js
- client/js/jsonedit.js
- tests/testcafe/functions.js
Fixes #1974. When changing the `id` of a widget using the JSON editor, the editor selection will now be updated to the new id.
> fixed crash after renaming a widget

- README.md
I wrote https://github.com/ArnoldSmith86/virtualtabletop-misc/blob/main/android-termux.sh today that makes it very easy to start a server on Android. So I thought, I should put it into the readme.
> added Android server instructions to the readme

- client/js/editor/toolbarButton.js
Oops, an oversight in #2219 caused the Game Shelf button to be disabled whenever the editor was opened.
> fixed disabled game shelf

- client/css/jsonedit.css
- client/js/editor/sidebar/json.js
- client/js/jsonedit.js
Fixes #2222 and #2187. Changing `type` or `id` should now always keep the selection and tree updated. The same should be true for changing multi-selection using the `widget` section in the JSON editor (including using regular expressions).
It is really nice that manipulating multi-selection is so much faster after #2211. Should make it a lot more useful.
> fixed selection behavior for multi-select and changing id or type

- client/js/mousehandling.js
- client/js/widgets/widget.js
Any widget can now define `hotkey` and it will be clicked whenever the given key is pressed.
Policy for public library games should be that it's never _required_ to use the key so that all games still work on touchscreens IMO.
> added property `hotkey`

- library/games/Egyptian Epochs/0.json
- library/games/Egyptian Epochs/1.json
- library/games/Egyptian Epochs/2.json
Updates to the public library game _Egyptian Epochs_.
Most notably:
- Add the ability for players to toggle "Pass" during the auction by clicking on the bid holder to show an "x" there. (This is also now mentioned in the module usage instructions.)
- Add a transition animation so it's clearer when a tile, especially a Horus tile, is drawn with the "Draw Tile" button.
Also a few other minor tweaks:
- Fix a 2-pixel misalignment of the New Game and New Epoch buttons
- Fix a slight difference in the shade of red on two types of disaster tile
- Reword the pharaoh tile scoring aid text to try and avoid a rendering issue reported by some issues on Chrome/Brave on Windows 10
> PL Egyptian Epochs: Usability Improvements

- client/js/jsonedit.js
You can now use the syntax `image:game-icons` in the filter box above the widget tree and in the `widgets` part of the JSON editor multi-selection mode. It will then display/select all widgets that contain `game-icons` (case-insensitive) in their `image` property.
It could be expanded to support regular expressions as well or check multiple properties but that feels like overkill.
The idea for this came when I found widgets with a property that was clearly a copy-paste error and I wanted to know if there were more of them.
> added property search to multi-select and tree filter

- library/games/Egyptian Epochs/0.json
- library/games/Egyptian Epochs/1.json
- library/games/Egyptian Epochs/2.json
Reset the new pass markers added in #2231 so that they reset to the blank side when the End Turn button is clicked, as well as when the Win buttons are used.
> PL Egyptian Epochs: Reset pass markers when End Turn pressed

- client/js/editor/sidebar/properties.js
- client/js/jsonedit.js
- client/js/widgets/canvas.js
- client/js/widgets/card.js
- client/js/widgets/pile.js
- client/js/widgets/widget.js
While testing #1538, we noticed that using an actual number as an `id` leads to crashes.
I searched for occurences of `widget.get(property).function` in the code to see where we are having similar issues. Because `widget.get(property)` can basically always return something that does not know `function`.
This PR fixes a couple of obvious places but there are probably still plenty more. It is already hard enough to review and test the scope as it is.
There are still plenty of crashes for widgets with actual numbers as their `id`. But now I know that the only real solution is to enforce strings for `id`. I will do that in a separate PR though.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2312/pr-test (or any other room on that server)
> fixed a few crashes when properties have unexpected types

- client/js/jsonedit.js
- client/js/serverstate.js
- client/js/widgets/widget.js
It currently just crashes if it is anything else and it really is not worth it to allow it.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2313/pr-test (or any other room on that server)
> enforce `id` to be a string

- client/js/serverstate.js
Fixes #2315. Was missing from #1538.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2316/pr-test (or any other room on that server)
> also update `dropTarget` when a widget `id` changes

- client/js/widgets/widget.js
I have no idea how this happened with #1466 but the default for `MOVE` is currently to not move anything if it uses a `collection`.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2321/pr-test (or any other room on that server)
> fixed default `count` for `MOVE`

- client/js/editor/sidebar/properties.js
The widgets in the visualizations in the Properties sidebar are not quite complete widgets. Apparently they need one hack more now. :)
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2325/pr-test (or any other room on that server)
> fixed crash when opening deck properties

- client/js/mousehandling.js
#2113 used a wrong variable that is not defined for touch events. Apparently this problem does not surface by breaking anything else. #2329 made it visible. This should fix it.
Hopefully the production server can get back to the latest version in `main` with this.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2337/pr-test (or any other room on that server)
> fixed cursor check client crash on touch devices

- client/js/editor/selection.js
When in edit mode in Firefox, the client crashes when you try to drag a widget to outside of the browser window. This PR should fix that.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2340/pr-test (or any other room on that server)
> fixed crash when dragging widget off screen

- client/css/layout.css
- client/js/overlays/players.js
Fixes #2373.
The toolbar Players tooltip now displays the active player count.  If the player count changes or if a player changes their name, then the icon and the tooltip turn yellow for a second and then back to white.  If the window size does not show the tooltip, then the player count is not shown but the yellow flash still happens on the icon.
The effect is subtle.  We could add a small sound to accompany the change.  Lots of apps do that.  But we don't have any other sounds and I don't want this to be annoying.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2376/pr-test (or any other room on that server)
> Add player count to toolbar

- client/js/overlays/players.js
Fixes #2351. Looks like it is possible for a client to receive a new players mouse state before knowing about its existance. This PR makes sure that each client only tries to render cursors for known players.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2382/pr-test (or any other room on that server)
> fixed crash when renaming

- client/js/jsonedit.js
Fixes #2341. Caused by #2041. This seems to be the most frequent client crash.
Receiving a delta while you're editing a widget and you currently have invalid JSON in your editor.
Behavior in production:
[cinnamon-2024-12-03T124855+0100.webm](https://github.com/user-attachments/assets/405bed08-cf26-4c71-ae34-439571985d1d)
Behavior before #2041:
[cinnamon-2024-12-03T124807+0100.webm](https://github.com/user-attachments/assets/711b9ba1-c27b-4182-addc-72320640d51c)
Behavior with this PR:
[cinnamon-2024-12-03T124555+0100.webm](https://github.com/user-attachments/assets/3d64074e-0e26-40cb-b726-a06dfb56655a)
---
So now the JSON editor tries to apply the changes from the delta to the invalid JSON. If it can't, it appends them to the editor for the user to merge.
---
PR-SERVER-BOT: You can play …
> fixed crash when receiving a delta while having invalid JSON

- client/css/jsonedit.css
- client/js/jsonedit.js
Fixes #2314.  Removes the toggle-wide button which is not needed with the new UI. Also permanently displays the additional (red) details in the tree for cards, buttons, and classes.  I played around with settings for various widths, but I think it makes the most sense just to always display this.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2414/pr-test (or any other room on that server)
> Show anonymous widget details in the tree view

- client/js/domhelpers.js
Fixes #2433.
The problem exists on 3 buttons. This solution simply checks if the cursor is in a textbox and does not open the overlay if it is not.  A better solution would somehow find which textbox the button is associated with and put the cursor at the end of any text that is there and then open the overlay.  But I couldn't figure that out.
This does not impact game play, only editing certain game metadata, so not a critical bug, but one we should fix.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2434/pr-test (or any other room on that server)
> Fix Symbol Picker Client Crash

- library/games/Crossed/0.json
When clicking the dice, you could no longer see which face was active. It was fine but why not keep it visible?
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2495/pr-test (or any other room on that server)
> Public Library - Improve Crossed dice visibility

- .github/workflows/docker-publish.yml
- README-DOCKER.md
This PR _should_ (hard to test) create a second tag for the official Docker image that excludes the public library. If somebody does not want to use the library, it is a lot of unnecessary data.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2515/pr-test (or any other room on that server)
> added Docker image without library

- client/js/widgets/widget.js
When we introduced `display` in #2167, we did not notice that seats already had a `display` property.
This lead to `display: ""` on seats changing from showing a blank seat to hiding the seat completely.
This PR should make them blank again.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2523/pr-test (or any other room on that server)
> fixed empty `display` for seats

- library/games/A Night on_ Town/0.json
PL Game "A Night on' Town": User feedback was that it can be hard to determine that the visible coins are a personal supply vs. a general supply.
This update addresses this issue, both in-game and in the _How to use this implementation_ section.
(Authored by Mitchell Stolycia as already credited in Attribution section.)
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2539/pr-test (or any other room on that server)
> PL A Night on' Town: Make personal money supply clearer

- client/css/jsonedit.css
Something changed in Chrome 135 that made highlighted text in the editor invisible. This should fix it.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2543/pr-test (or any other room on that server)
> fixed text highlighting in Chrome

- library/games/Score Keeper/0.json
- library/games/Score Keeper/1.json
The original version was very difficult to use on mobile because the buttons were small.  This update reduces the number of possible players from 13 to 8 in order to increase the size of buttons and the score table.  Definitely worth the trade off as the number of games with more than 8 players is very small.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2572/pr-test (or any other room on that server)
> Public Library - Update Score Keeper

- client/js/editor/layout.js
- client/js/editor/sidebar/json.js
- client/js/jsonedit.js
- tests/testcafe/functions.js
Writing the routine debug output is very slow for more complex routines. This PR only enables the debug logging when the Debug sidebar is actually active.
It also not longer calls the function to apply the current log filter to new debug output when no filter is set.
---
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-2635/pr-test (or any other room on that server)
> less unneeded debug logging
